// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aerospike/aerospike-backup-service/v3/pkg/service/preflight (interfaces: Checker)
//
// Generated by this command:
//
//	mockgen -package preflight -destination pkg/service/preflight/mockgen.go github.com/aerospike/aerospike-backup-service/v3/pkg/service/preflight Checker
//

// Package preflight is a generated GoMock package.
package preflight

import (
	context "context"
	reflect "reflect"

	model "github.com/aerospike/aerospike-backup-service/v3/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// MockChecker is a mock of Checker interface.
type MockChecker struct {
	ctrl     *gomock.Controller
	recorder *MockCheckerMockRecorder
	isgomock struct{}
}

// MockCheckerMockRecorder is the mock recorder for MockChecker.
type MockCheckerMockRecorder struct {
	mock *MockChecker
}

// NewMockChecker creates a new mock instance.
func NewMockChecker(ctrl *gomock.Controller) *MockChecker {
	mock := &MockChecker{ctrl: ctrl}
	mock.recorder = &MockCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChecker) EXPECT() *MockCheckerMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockChecker) Check(ctx context.Context, config *model.Config) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Check", ctx, config)
}

// Check indicates an expected call of Check.
func (mr *MockCheckerMockRecorder) Check(ctx, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockChecker)(nil).Check), ctx, config)
}

// CheckChanges mocks base method.
func (m *MockChecker) CheckChanges(ctx context.Context, previous, current *model.Config) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CheckChanges", ctx, previous, current)
}

// CheckChanges indicates an expected call of CheckChanges.
func (mr *MockCheckerMockRecorder) CheckChanges(ctx, previous, current any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckChanges", reflect.TypeOf((*MockChecker)(nil).CheckChanges), ctx, previous, current)
}
