// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aerospike/aerospike-backup-service/v3/pkg/service/preflight (interfaces: Checker)
//
// Generated by this command:
//
//	mockgen -package preflight -destination pkg/service/preflight/mockgen.go github.com/aerospike/aerospike-backup-service/v3/pkg/service/preflight Checker
//

// Package preflight is a generated GoMock package.
package preflight

import (
	context "context"
	reflect "reflect"

	model "github.com/aerospike/aerospike-backup-service/v3/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// MockChecker is a mock of Checker interface.
type MockChecker struct {
	ctrl     *gomock.Controller
	recorder *MockCheckerMockRecorder
	isgomock struct{}
}

// MockCheckerMockRecorder is the mock recorder for MockChecker.
type MockCheckerMockRecorder struct {
	mock *MockChecker
}

// NewMockChecker creates a new mock instance.
func NewMockChecker(ctrl *gomock.Controller) *MockChecker {
	mock := &MockChecker{ctrl: ctrl}
	mock.recorder = &MockCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChecker) EXPECT() *MockCheckerMockRecorder {
	return m.recorder
}

// RequestCheck mocks base method.
func (m *MockChecker) RequestCheck(previous, current *model.BackupConfig) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RequestCheck", previous, current)
}

// RequestCheck indicates an expected call of RequestCheck.
func (mr *MockCheckerMockRecorder) RequestCheck(previous, current any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestCheck", reflect.TypeOf((*MockChecker)(nil).RequestCheck), previous, current)
}

// Start mocks base method.
func (m *MockChecker) Start(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start", ctx)
}

// Start indicates an expected call of Start.
func (mr *MockCheckerMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockChecker)(nil).Start), ctx)
}
