// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aerospike/aerospike-backup-service/v3/internal/server/tlsconfig (interfaces: Prober)
//
// Generated by this command:
//
//	mockgen -package tlsconfig -destination internal/server/tlsconfig/mockgen.go github.com/aerospike/aerospike-backup-service/v3/internal/server/tlsconfig Prober
//

// Package tlsconfig is a generated GoMock package.
package tlsconfig

import (
	context "context"
	reflect "reflect"

	model "github.com/aerospike/aerospike-backup-service/v3/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// MockProber is a mock of Prober interface.
type MockProber struct {
	ctrl     *gomock.Controller
	recorder *MockProberMockRecorder
	isgomock struct{}
}

// MockProberMockRecorder is the mock recorder for MockProber.
type MockProberMockRecorder struct {
	mock *MockProber
}

// NewMockProber creates a new mock instance.
func NewMockProber(ctrl *gomock.Controller) *MockProber {
	mock := &MockProber{ctrl: ctrl}
	mock.recorder = &MockProberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProber) EXPECT() *MockProberMockRecorder {
	return m.recorder
}

// ProbeConfig mocks base method.
func (m *MockProber) ProbeConfig(ctx context.Context, config *model.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProbeConfig", ctx, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProbeConfig indicates an expected call of ProbeConfig.
func (mr *MockProberMockRecorder) ProbeConfig(ctx, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProbeConfig", reflect.TypeOf((*MockProber)(nil).ProbeConfig), ctx, config)
}
