// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aerospike/backup-go (interfaces: StreamingReader)
//
// Generated by this command:
//
//	mockgen -package restoreexecutor -destination pkg/service/restoreexecutor/backupgo_mockgen.go github.com/aerospike/backup-go StreamingReader
//

// Package restoreexecutor is a generated GoMock package.
package restoreexecutor

import (
	context "context"
	reflect "reflect"

	models "github.com/aerospike/backup-go/models"
	gomock "go.uber.org/mock/gomock"
)

// MockStreamingReader is a mock of StreamingReader interface.
type MockStreamingReader struct {
	ctrl     *gomock.Controller
	recorder *MockStreamingReaderMockRecorder
	isgomock struct{}
}

// MockStreamingReaderMockRecorder is the mock recorder for MockStreamingReader.
type MockStreamingReaderMockRecorder struct {
	mock *MockStreamingReader
}

// NewMockStreamingReader creates a new mock instance.
func NewMockStreamingReader(ctrl *gomock.Controller) *MockStreamingReader {
	mock := &MockStreamingReader{ctrl: ctrl}
	mock.recorder = &MockStreamingReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamingReader) EXPECT() *MockStreamingReaderMockRecorder {
	return m.recorder
}

// GetNumber mocks base method.
func (m *MockStreamingReader) GetNumber() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNumber")
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetNumber indicates an expected call of GetNumber.
func (mr *MockStreamingReaderMockRecorder) GetNumber() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNumber", reflect.TypeOf((*MockStreamingReader)(nil).GetNumber))
}

// GetSize mocks base method.
func (m *MockStreamingReader) GetSize() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSize")
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetSize indicates an expected call of GetSize.
func (mr *MockStreamingReaderMockRecorder) GetSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSize", reflect.TypeOf((*MockStreamingReader)(nil).GetSize))
}

// GetSkipped mocks base method.
func (m *MockStreamingReader) GetSkipped() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSkipped")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetSkipped indicates an expected call of GetSkipped.
func (mr *MockStreamingReaderMockRecorder) GetSkipped() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSkipped", reflect.TypeOf((*MockStreamingReader)(nil).GetSkipped))
}

// GetType mocks base method.
func (m *MockStreamingReader) GetType() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetType")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetType indicates an expected call of GetType.
func (mr *MockStreamingReaderMockRecorder) GetType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetType", reflect.TypeOf((*MockStreamingReader)(nil).GetType))
}

// ListObjects mocks base method.
func (m *MockStreamingReader) ListObjects(ctx context.Context, path string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjects", ctx, path)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjects indicates an expected call of ListObjects.
func (mr *MockStreamingReaderMockRecorder) ListObjects(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjects", reflect.TypeOf((*MockStreamingReader)(nil).ListObjects), ctx, path)
}

// StreamFile mocks base method.
func (m *MockStreamingReader) StreamFile(ctx context.Context, filename string, readersCh chan<- models.File, errorsCh chan<- error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StreamFile", ctx, filename, readersCh, errorsCh)
}

// StreamFile indicates an expected call of StreamFile.
func (mr *MockStreamingReaderMockRecorder) StreamFile(ctx, filename, readersCh, errorsCh any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamFile", reflect.TypeOf((*MockStreamingReader)(nil).StreamFile), ctx, filename, readersCh, errorsCh)
}

// StreamFiles mocks base method.
func (m *MockStreamingReader) StreamFiles(arg0 context.Context, arg1 chan<- models.File, arg2 chan<- error, arg3 []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StreamFiles", arg0, arg1, arg2, arg3)
}

// StreamFiles indicates an expected call of StreamFiles.
func (mr *MockStreamingReaderMockRecorder) StreamFiles(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamFiles", reflect.TypeOf((*MockStreamingReader)(nil).StreamFiles), arg0, arg1, arg2, arg3)
}
