// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aerospike/aerospike-backup-service/v3/pkg/service/restoreexecutor (interfaces: Restore,RestoreHandler)
//
// Generated by this command:
//
//	mockgen -package restoreexecutor -destination pkg/service/restoreexecutor/mockgen.go github.com/aerospike/aerospike-backup-service/v3/pkg/service/restoreexecutor Restore,RestoreHandler
//

// Package restoreexecutor is a generated GoMock package.
package restoreexecutor

import (
	context "context"
	reflect "reflect"

	model "github.com/aerospike/aerospike-backup-service/v3/pkg/model"
	aerospike "github.com/aerospike/aerospike-backup-service/v3/pkg/service/aerospike"
	models "github.com/aerospike/backup-go/models"
	gomock "go.uber.org/mock/gomock"
)

// MockRestore is a mock of Restore interface.
type MockRestore struct {
	ctrl     *gomock.Controller
	recorder *MockRestoreMockRecorder
	isgomock struct{}
}

// MockRestoreMockRecorder is the mock recorder for MockRestore.
type MockRestoreMockRecorder struct {
	mock *MockRestore
}

// NewMockRestore creates a new mock instance.
func NewMockRestore(ctrl *gomock.Controller) *MockRestore {
	mock := &MockRestore{ctrl: ctrl}
	mock.recorder = &MockRestoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRestore) EXPECT() *MockRestoreMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockRestore) Run(ctx context.Context, client aerospike.Restorer, restoreRequest *model.RestoreRequest) (RestoreHandler, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, client, restoreRequest)
	ret0, _ := ret[0].(RestoreHandler)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockRestoreMockRecorder) Run(ctx, client, restoreRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockRestore)(nil).Run), ctx, client, restoreRequest)
}

// MockRestoreHandler is a mock of RestoreHandler interface.
type MockRestoreHandler struct {
	ctrl     *gomock.Controller
	recorder *MockRestoreHandlerMockRecorder
	isgomock struct{}
}

// MockRestoreHandlerMockRecorder is the mock recorder for MockRestoreHandler.
type MockRestoreHandlerMockRecorder struct {
	mock *MockRestoreHandler
}

// NewMockRestoreHandler creates a new mock instance.
func NewMockRestoreHandler(ctrl *gomock.Controller) *MockRestoreHandler {
	mock := &MockRestoreHandler{ctrl: ctrl}
	mock.recorder = &MockRestoreHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRestoreHandler) EXPECT() *MockRestoreHandlerMockRecorder {
	return m.recorder
}

// GetMetrics mocks base method.
func (m *MockRestoreHandler) GetMetrics() *models.Metrics {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetrics")
	ret0, _ := ret[0].(*models.Metrics)
	return ret0
}

// GetMetrics indicates an expected call of GetMetrics.
func (mr *MockRestoreHandlerMockRecorder) GetMetrics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetrics", reflect.TypeOf((*MockRestoreHandler)(nil).GetMetrics))
}

// GetStats mocks base method.
func (m *MockRestoreHandler) GetStats() *models.RestoreStats {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats")
	ret0, _ := ret[0].(*models.RestoreStats)
	return ret0
}

// GetStats indicates an expected call of GetStats.
func (mr *MockRestoreHandlerMockRecorder) GetStats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockRestoreHandler)(nil).GetStats))
}

// Wait mocks base method.
func (m *MockRestoreHandler) Wait(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Wait", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Wait indicates an expected call of Wait.
func (mr *MockRestoreHandlerMockRecorder) Wait(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wait", reflect.TypeOf((*MockRestoreHandler)(nil).Wait), arg0)
}
