# dependable.yml configuration for Aerospike Backup Service
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates once a month
      interval: "monthly"
    groups:
      # Group all updates into a single PR named 'github-actions-dependencies'
      github-actions-dependencies:
        patterns:
          - "*"
    # Limit to 1 open PR to avoid clutter
    open-pull-requests-limit: 1

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      # Check for updates once a month
      interval: "monthly"
    groups:
      # Group all updates into a single PR named 'docker-dependencies'
      docker-dependencies:
        patterns:
          - "*"
    # Limit to 1 open PR to avoid clutter
    open-pull-requests-limit: 1

  # Maintain dependencies for Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      # Check for updates once a month
      interval: "monthly"
    groups:
      # Group all updates into a single PR named 'gomod-dependencies'
      gomod-dependencies:
        patterns:
          - "*"
    # Limit to 1 open PR to avoid clutter
    open-pull-requests-limit: 1
