version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - fatcontext
    - funlen
    - goconst
    - gocritic
    - gocognit
    - gocyclo
    - godot
    - gosec
    - govet
    - ineffassign
    - intrange
    - lll
    - misspell
    - modernize
    - nakedret
    - nestif
    - nlreturn
    - nolintlint
    - nilerr
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - sloglint
    - staticcheck
    - tagliatelle
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    godot:
      exclude:
        - '@(Success|Failure|Router).*'
    gosec:
      excludes:
        - G115
    gocognit:
      min-complexity: 25
    exhaustive:
      default-signifies-exhaustive: true
    nlreturn:
      block-size: 10
    tagliatelle:
      case:
        rules:
          json: kebab
          yaml: kebab
    sloglint:
      attr-only: true
      key-naming-case: camel
      forbidden-keys:
        - err
    revive:
      rules:
        - name: exported
          arguments:
            - checkPublicInterface
            - checkPrivateReceivers
          exclude:
            - test
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - funlen
          - goconst
          - nlreturn
          - prealloc
          - unparam
        path: _test\.go
    paths:
      - examples
      - modules
      - docs
      - docker
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - examples
      - modules
      - docs
      - docker
      - third_party$
      - builtin$
      - examples$
