// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aerospike/aerospike-backup-service/v3/internal/server/configuration (interfaces: storageReaderWriter)
//
// Generated by this command:
//
//	mockgen -package configuration -destination internal/server/configuration/mockgen.go github.com/aerospike/aerospike-backup-service/v3/internal/server/configuration storageReaderWriter
//

// Package configuration is a generated GoMock package.
package configuration

import (
	context "context"
	reflect "reflect"

	model "github.com/aerospike/aerospike-backup-service/v3/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// MockstorageReaderWriter is a mock of storageReaderWriter interface.
type MockstorageReaderWriter struct {
	ctrl     *gomock.Controller
	recorder *MockstorageReaderWriterMockRecorder
	isgomock struct{}
}

// MockstorageReaderWriterMockRecorder is the mock recorder for MockstorageReaderWriter.
type MockstorageReaderWriterMockRecorder struct {
	mock *MockstorageReaderWriter
}

// NewMockstorageReaderWriter creates a new mock instance.
func NewMockstorageReaderWriter(ctrl *gomock.Controller) *MockstorageReaderWriter {
	mock := &MockstorageReaderWriter{ctrl: ctrl}
	mock.recorder = &MockstorageReaderWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockstorageReaderWriter) EXPECT() *MockstorageReaderWriterMockRecorder {
	return m.recorder
}

// ReadFile mocks base method.
func (m *MockstorageReaderWriter) ReadFile(ctx context.Context, storage model.Storage, filepath string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFile", ctx, storage, filepath)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFile indicates an expected call of ReadFile.
func (mr *MockstorageReaderWriterMockRecorder) ReadFile(ctx, storage, filepath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*MockstorageReaderWriter)(nil).ReadFile), ctx, storage, filepath)
}

// WriteDataFile mocks base method.
func (m *MockstorageReaderWriter) WriteDataFile(ctx context.Context, storage model.Storage, fileName string, content []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteDataFile", ctx, storage, fileName, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteDataFile indicates an expected call of WriteDataFile.
func (mr *MockstorageReaderWriterMockRecorder) WriteDataFile(ctx, storage, fileName, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteDataFile", reflect.TypeOf((*MockstorageReaderWriter)(nil).WriteDataFile), ctx, storage, fileName, content)
}
