// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aerospike/aerospike-backup-service/v3/internal/server/configuration (interfaces: storageReaderWriter)
//
// Generated by this command:
//
//	mockgen -package configuration -destination internal/server/configuration/mockgen.go -mock_names=storageReaderWriter=mockStorageReaderWriter github.com/aerospike/aerospike-backup-service/v3/internal/server/configuration storageReaderWriter
//

// Package configuration is a generated GoMock package.
package configuration

import (
	context "context"
	reflect "reflect"

	model "github.com/aerospike/aerospike-backup-service/v3/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// mockStorageReaderWriter is a mock of storageReaderWriter interface.
type mockStorageReaderWriter struct {
	ctrl     *gomock.Controller
	recorder *mockStorageReaderWriterMockRecorder
	isgomock struct{}
}

// mockStorageReaderWriterMockRecorder is the mock recorder for mockStorageReaderWriter.
type mockStorageReaderWriterMockRecorder struct {
	mock *mockStorageReaderWriter
}

// NewmockStorageReaderWriter creates a new mock instance.
func NewmockStorageReaderWriter(ctrl *gomock.Controller) *mockStorageReaderWriter {
	mock := &mockStorageReaderWriter{ctrl: ctrl}
	mock.recorder = &mockStorageReaderWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *mockStorageReaderWriter) EXPECT() *mockStorageReaderWriterMockRecorder {
	return m.recorder
}

// ReadFile mocks base method.
func (m *mockStorageReaderWriter) ReadFile(ctx context.Context, storage model.Storage, filepath string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFile", ctx, storage, filepath)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFile indicates an expected call of ReadFile.
func (mr *mockStorageReaderWriterMockRecorder) ReadFile(ctx, storage, filepath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*mockStorageReaderWriter)(nil).ReadFile), ctx, storage, filepath)
}

// WriteDataFile mocks base method.
func (m *mockStorageReaderWriter) WriteDataFile(ctx context.Context, storage model.Storage, fileName string, content []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteDataFile", ctx, storage, fileName, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteDataFile indicates an expected call of WriteDataFile.
func (mr *mockStorageReaderWriterMockRecorder) WriteDataFile(ctx, storage, fileName, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteDataFile", reflect.TypeOf((*mockStorageReaderWriter)(nil).WriteDataFile), ctx, storage, fileName, content)
}
