apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aerospike-backup-service
  name: aerospike-backup-service
  namespace: aerospike
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aerospike-backup-service
  template:
    metadata:
      labels:
        app: aerospike-backup-service
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - aerospike-backup-service
              topologyKey: kubernetes.io/hostname
      automountServiceAccountToken: true
      containers:
        - name: aerospike-backup-service
          image: aerospike.jfrog.io/ecosystem-container-prod-local/aerospike-backup-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /etc/aerospike-backup-service/aerospike-backup-service.yml
              name: backup-config
              subPath: aerospike-backup-service.yml
            - mountPath: /config/psw.txt
              name: psw
              readOnly: true
              subPath: psw.txt
            - mountPath: /etc/aerospike-backup-service/ssl/rootCA.pem
              name: tls
              readOnly: true
              subPath: rootCA.pem
      restartPolicy: Always
      serviceAccountName: backup-service
      volumes:
        - configMap:
            name: aerospike-backup-service-cm
            optional: true
          name: backup-config
        - name: psw
          secret:
            optional: true
            secretName: psw-cm
        - name: tls
          secret:
            optional: true
            secretName: backup-service-tls-secret
