apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aerospike-backup-service
  name: aerospike-backup-service
  namespace: aerospike
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aerospike-backup-service
  template:
    metadata:
      labels:
        app: aerospike-backup-service
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - aerospike-backup-service
              topologyKey: kubernetes.io/hostname
      automountServiceAccountToken: true
      containers:
        - name: aerospike-backup-service
          image: aerospike.jfrog.io/ecosystem-container-prod-local/aerospike-backup-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /etc/aerospike-backup-service/aerospike-backup-service.yml
              name: backup-config
              subPath: aerospike-backup-service.yml
      restartPolicy: Always
      serviceAccountName: backup-service
      volumes:
        - configMap:
            name: aerospike-backup-service-cm
            optional: true
          name: backup-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: aerospike-backup-service
  name: aerospike-backup-service
  namespace: aerospike
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: aerospike-backup-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aerospike-backup-service-cm
  namespace: aerospike
data:
  aerospike-backup-service.yml: |
    "aerospike-clusters":
      "absCluster1":
        "credentials":
          "password": "psw"
          "user": "tester"
        "seed-nodes":
          - "host-name": "abs-cluster.internal"
            "port": 3000
    "backup-policies":
      "keepFilesPolicy":
        "parallel": 1
        "remove-files": false
        "type": 1
    "backup-routines":
      "keepFilesRoutine":
        "backup-policy": "keepFilesPolicy"
        "interval-cron": "@daily"
        "namespace": "test"
        "source-cluster": "absCluster1"
        "storage": "s3Storage"
    "storage":
      "s3Storage":
        "path": "s3://abs-backup-bucket/s3Storage"
        "s3-endpoint-override": ""
        "s3-profile": ""
        "s3-region": "eu-central-1"
        "type": 1
