#!/usr/bin/env bash
# Recreates testdata/ with OpenSSL 3. Everything in it is test-only: 100-year validity,
# the password from fixtures.go, no relation to any deployment. Rerun after changing this
# script and commit the result.
set -euo pipefail

cd "$(dirname "$0")"
openssl version | grep -q '^OpenSSL 3' || { echo "OpenSSL 3 required, found: $(openssl version)" >&2; exit 1; }

out=testdata
pass=pass:fixture-password
days=36500
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT
rm -rf "$out"
mkdir -p "$out"

# Two CAs, each as plain PEM and as `openssl x509 -text` output, plus a bundle with a dump before each.
for ca in ca ca2; do
  openssl req -x509 -newkey rsa:2048 -nodes -keyout "$work/$ca.key" -out "$out/$ca.pem" \
    -days "$days" -subj "/CN=ABS test $ca"
  openssl x509 -in "$out/$ca.pem" -text -out "$out/$ca-text.pem"
done
cat "$out/ca-text.pem" "$out/ca2-text.pem" > "$out/ca-bundle-text.pem"

# One server key per algorithm in every encoding OpenSSL writes, with a self-signed certificate each.
openssl genrsa -out "$work/rsa.key" 2048
openssl ecparam -name prime256v1 -genkey -noout -out "$work/ec.key"
openssl genpkey -algorithm ed25519 -out "$work/ed25519.key"
for alg in rsa ec ed25519; do
  openssl req -x509 -key "$work/$alg.key" -out "$out/$alg-cert.pem" -days "$days" -subj /CN=localhost \
    -addext subjectAltName=DNS:localhost,IP:127.0.0.1
  openssl pkcs8 -topk8 -nocrypt -in "$work/$alg.key" -out "$out/$alg-key-pkcs8.pem"
  openssl pkcs8 -topk8 -in "$work/$alg.key" -passout "$pass" -out "$out/$alg-key-pkcs8-aes256.pem"
  openssl pkcs8 -topk8 -scrypt -in "$work/$alg.key" -passout "$pass" -out "$out/$alg-key-pkcs8-scrypt.pem"
done
# Algorithm-specific encodings: PKCS#1 and SEC1, plain and with legacy RFC 1423 encryption.
openssl rsa -in "$work/rsa.key" -traditional -out "$out/rsa-key-pkcs1.pem"
openssl rsa -in "$work/rsa.key" -traditional -aes256 -passout "$pass" -out "$out/rsa-key-pkcs1-aes256.pem"
openssl ec -in "$work/ec.key" -out "$out/ec-key-sec1.pem"
openssl ec -in "$work/ec.key" -aes256 -passout "$pass" -out "$out/ec-key-sec1-aes256.pem"

# CRLs from each CA: PEM, DER, `openssl crl -text` output, and a bundle with a dump before each.
# The first CA revokes one certificate so its CRL carries an entry.
for ca in ca ca2; do
  mkdir -p "$work/$ca-db"
  : > "$work/$ca-db/index.txt"
  echo 01 > "$work/$ca-db/crlnumber"
  cat > "$work/$ca.cnf" <<CNF
[ca]
default_ca = CA_default
[CA_default]
database = $work/$ca-db/index.txt
crlnumber = $work/$ca-db/crlnumber
certificate = $out/$ca.pem
private_key = $work/$ca.key
default_md = sha256
default_crl_days = $days
CNF
done
openssl req -newkey rsa:2048 -nodes -keyout "$work/client.key" -out "$work/client.csr" -subj "/CN=revoked client"
openssl x509 -req -in "$work/client.csr" -CA "$out/ca.pem" -CAkey "$work/ca.key" \
  -CAcreateserial -CAserial "$work/ca.srl" -days "$days" -out "$work/client.pem"
openssl ca -config "$work/ca.cnf" -revoke "$work/client.pem"
openssl ca -config "$work/ca.cnf" -gencrl -out "$out/crl.pem"
openssl crl -in "$out/crl.pem" -outform DER -out "$out/crl.der"
openssl crl -in "$out/crl.pem" -text -out "$out/crl-text.pem"
openssl ca -config "$work/ca2.cnf" -gencrl -out "$work/crl2.pem"
openssl crl -in "$work/crl2.pem" -text -out "$work/crl2-text.pem"
cat "$out/crl-text.pem" "$work/crl2-text.pem" > "$out/crl-bundle-text.pem"

echo "generated by generate.sh with $(openssl version) on $(date -u +%Y-%m-%d)" > "$out/VERSION"
