// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aerospike/backup-go (interfaces: InfoGetter,AerospikeClient)
//
// Generated by this command:
//
//	mockgen -package aerospike -destination pkg/service/aerospike/backupgo_mockgen.go github.com/aerospike/backup-go InfoGetter,AerospikeClient
//

// Package aerospike is a generated GoMock package.
package aerospike

import (
	context "context"
	reflect "reflect"

	aerospike "github.com/aerospike/aerospike-client-go/v8"
	models "github.com/aerospike/backup-go/models"
	models0 "github.com/aerospike/backup-go/pkg/asinfo/models"
	gomock "go.uber.org/mock/gomock"
)

// MockInfoGetter is a mock of InfoGetter interface.
type MockInfoGetter struct {
	ctrl     *gomock.Controller
	recorder *MockInfoGetterMockRecorder
	isgomock struct{}
}

// MockInfoGetterMockRecorder is the mock recorder for MockInfoGetter.
type MockInfoGetterMockRecorder struct {
	mock *MockInfoGetter
}

// NewMockInfoGetter creates a new mock instance.
func NewMockInfoGetter(ctrl *gomock.Controller) *MockInfoGetter {
	mock := &MockInfoGetter{ctrl: ctrl}
	mock.recorder = &MockInfoGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInfoGetter) EXPECT() *MockInfoGetterMockRecorder {
	return m.recorder
}

// GetBackupStatus mocks base method.
func (m *MockInfoGetter) GetBackupStatus(ctx context.Context, jobID string) (*models0.ResponseBackupState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBackupStatus", ctx, jobID)
	ret0, _ := ret[0].(*models0.ResponseBackupState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBackupStatus indicates an expected call of GetBackupStatus.
func (mr *MockInfoGetterMockRecorder) GetBackupStatus(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBackupStatus", reflect.TypeOf((*MockInfoGetter)(nil).GetBackupStatus), ctx, jobID)
}

// GetClusterStable mocks base method.
func (m *MockInfoGetter) GetClusterStable(ctx context.Context, namespace string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClusterStable", ctx, namespace)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClusterStable indicates an expected call of GetClusterStable.
func (mr *MockInfoGetterMockRecorder) GetClusterStable(ctx, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClusterStable", reflect.TypeOf((*MockInfoGetter)(nil).GetClusterStable), ctx, namespace)
}

// GetNamespacesList mocks base method.
func (m *MockInfoGetter) GetNamespacesList(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNamespacesList", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNamespacesList indicates an expected call of GetNamespacesList.
func (mr *MockInfoGetterMockRecorder) GetNamespacesList(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNamespacesList", reflect.TypeOf((*MockInfoGetter)(nil).GetNamespacesList), ctx)
}

// GetPendingMigrations mocks base method.
func (m *MockInfoGetter) GetPendingMigrations(ctx context.Context, namespace string) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingMigrations", ctx, namespace)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingMigrations indicates an expected call of GetPendingMigrations.
func (mr *MockInfoGetterMockRecorder) GetPendingMigrations(ctx, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingMigrations", reflect.TypeOf((*MockInfoGetter)(nil).GetPendingMigrations), ctx, namespace)
}

// GetPrimaryPartitions mocks base method.
func (m *MockInfoGetter) GetPrimaryPartitions(ctx context.Context, node, namespace string) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrimaryPartitions", ctx, node, namespace)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrimaryPartitions indicates an expected call of GetPrimaryPartitions.
func (mr *MockInfoGetterMockRecorder) GetPrimaryPartitions(ctx, node, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrimaryPartitions", reflect.TypeOf((*MockInfoGetter)(nil).GetPrimaryPartitions), ctx, node, namespace)
}

// GetRackNodes mocks base method.
func (m *MockInfoGetter) GetRackNodes(ctx context.Context, rackID int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRackNodes", ctx, rackID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRackNodes indicates an expected call of GetRackNodes.
func (mr *MockInfoGetterMockRecorder) GetRackNodes(ctx, rackID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRackNodes", reflect.TypeOf((*MockInfoGetter)(nil).GetRackNodes), ctx, rackID)
}

// GetRecordCount mocks base method.
func (m *MockInfoGetter) GetRecordCount(ctx context.Context, namespace string, sets []string) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecordCount", ctx, namespace, sets)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecordCount indicates an expected call of GetRecordCount.
func (mr *MockInfoGetterMockRecorder) GetRecordCount(ctx, namespace, sets any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecordCount", reflect.TypeOf((*MockInfoGetter)(nil).GetRecordCount), ctx, namespace, sets)
}

// GetRestoreStatus mocks base method.
func (m *MockInfoGetter) GetRestoreStatus(ctx context.Context, namespace string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRestoreStatus", ctx, namespace)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRestoreStatus indicates an expected call of GetRestoreStatus.
func (mr *MockInfoGetterMockRecorder) GetRestoreStatus(ctx, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRestoreStatus", reflect.TypeOf((*MockInfoGetter)(nil).GetRestoreStatus), ctx, namespace)
}

// GetSIndexes mocks base method.
func (m *MockInfoGetter) GetSIndexes(ctx context.Context, namespace string) ([]*models.SIndex, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSIndexes", ctx, namespace)
	ret0, _ := ret[0].([]*models.SIndex)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSIndexes indicates an expected call of GetSIndexes.
func (mr *MockInfoGetterMockRecorder) GetSIndexes(ctx, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSIndexes", reflect.TypeOf((*MockInfoGetter)(nil).GetSIndexes), ctx, namespace)
}

// GetService mocks base method.
func (m *MockInfoGetter) GetService(ctx context.Context, node string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetService", ctx, node)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetService indicates an expected call of GetService.
func (mr *MockInfoGetterMockRecorder) GetService(ctx, node any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetService", reflect.TypeOf((*MockInfoGetter)(nil).GetService), ctx, node)
}

// GetSetsList mocks base method.
func (m *MockInfoGetter) GetSetsList(ctx context.Context, namespace string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSetsList", ctx, namespace)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSetsList indicates an expected call of GetSetsList.
func (mr *MockInfoGetterMockRecorder) GetSetsList(ctx, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSetsList", reflect.TypeOf((*MockInfoGetter)(nil).GetSetsList), ctx, namespace)
}

// GetStatus mocks base method.
func (m *MockInfoGetter) GetStatus(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockInfoGetterMockRecorder) GetStatus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockInfoGetter)(nil).GetStatus), ctx)
}

// GetUDFs mocks base method.
func (m *MockInfoGetter) GetUDFs(ctx context.Context) ([]*models.UDF, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUDFs", ctx)
	ret0, _ := ret[0].([]*models.UDF)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUDFs indicates an expected call of GetUDFs.
func (mr *MockInfoGetterMockRecorder) GetUDFs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUDFs", reflect.TypeOf((*MockInfoGetter)(nil).GetUDFs), ctx)
}

// GetVersion mocks base method.
func (m *MockInfoGetter) GetVersion(ctx context.Context) (models0.AerospikeVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersion", ctx)
	ret0, _ := ret[0].(models0.AerospikeVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVersion indicates an expected call of GetVersion.
func (mr *MockInfoGetterMockRecorder) GetVersion(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersion", reflect.TypeOf((*MockInfoGetter)(nil).GetVersion), ctx)
}

// HasExpressionSIndex mocks base method.
func (m *MockInfoGetter) HasExpressionSIndex(ctx context.Context, namespace string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasExpressionSIndex", ctx, namespace)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasExpressionSIndex indicates an expected call of HasExpressionSIndex.
func (mr *MockInfoGetterMockRecorder) HasExpressionSIndex(ctx, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasExpressionSIndex", reflect.TypeOf((*MockInfoGetter)(nil).HasExpressionSIndex), ctx, namespace)
}

// PrepareServerRestore mocks base method.
func (m *MockInfoGetter) PrepareServerRestore(ctx context.Context, jobID, namespace string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareServerRestore", ctx, jobID, namespace)
	ret0, _ := ret[0].(error)
	return ret0
}

// PrepareServerRestore indicates an expected call of PrepareServerRestore.
func (mr *MockInfoGetterMockRecorder) PrepareServerRestore(ctx, jobID, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareServerRestore", reflect.TypeOf((*MockInfoGetter)(nil).PrepareServerRestore), ctx, jobID, namespace)
}

// StartServerBackup mocks base method.
func (m *MockInfoGetter) StartServerBackup(ctx context.Context, request *models0.RequestBackup) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartServerBackup", ctx, request)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartServerBackup indicates an expected call of StartServerBackup.
func (mr *MockInfoGetterMockRecorder) StartServerBackup(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartServerBackup", reflect.TypeOf((*MockInfoGetter)(nil).StartServerBackup), ctx, request)
}

// StartServerRestore mocks base method.
func (m *MockInfoGetter) StartServerRestore(ctx context.Context, request *models0.RequestRestore) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartServerRestore", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartServerRestore indicates an expected call of StartServerRestore.
func (mr *MockInfoGetterMockRecorder) StartServerRestore(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartServerRestore", reflect.TypeOf((*MockInfoGetter)(nil).StartServerRestore), ctx, request)
}

// SupportsBatchWrite mocks base method.
func (m *MockInfoGetter) SupportsBatchWrite(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SupportsBatchWrite", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SupportsBatchWrite indicates an expected call of SupportsBatchWrite.
func (mr *MockInfoGetterMockRecorder) SupportsBatchWrite(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SupportsBatchWrite", reflect.TypeOf((*MockInfoGetter)(nil).SupportsBatchWrite), ctx)
}

// MockAerospikeClient is a mock of AerospikeClient interface.
type MockAerospikeClient struct {
	ctrl     *gomock.Controller
	recorder *MockAerospikeClientMockRecorder
	isgomock struct{}
}

// MockAerospikeClientMockRecorder is the mock recorder for MockAerospikeClient.
type MockAerospikeClientMockRecorder struct {
	mock *MockAerospikeClient
}

// NewMockAerospikeClient creates a new mock instance.
func NewMockAerospikeClient(ctrl *gomock.Controller) *MockAerospikeClient {
	mock := &MockAerospikeClient{ctrl: ctrl}
	mock.recorder = &MockAerospikeClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAerospikeClient) EXPECT() *MockAerospikeClientMockRecorder {
	return m.recorder
}

// BatchOperate mocks base method.
func (m *MockAerospikeClient) BatchOperate(policy *aerospike.BatchPolicy, records []aerospike.BatchRecordIfc) aerospike.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchOperate", policy, records)
	ret0, _ := ret[0].(aerospike.Error)
	return ret0
}

// BatchOperate indicates an expected call of BatchOperate.
func (mr *MockAerospikeClientMockRecorder) BatchOperate(policy, records any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchOperate", reflect.TypeOf((*MockAerospikeClient)(nil).BatchOperate), policy, records)
}

// Close mocks base method.
func (m *MockAerospikeClient) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockAerospikeClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockAerospikeClient)(nil).Close))
}

// Cluster mocks base method.
func (m *MockAerospikeClient) Cluster() *aerospike.Cluster {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cluster")
	ret0, _ := ret[0].(*aerospike.Cluster)
	return ret0
}

// Cluster indicates an expected call of Cluster.
func (mr *MockAerospikeClientMockRecorder) Cluster() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cluster", reflect.TypeOf((*MockAerospikeClient)(nil).Cluster))
}

// CreateComplexIndex mocks base method.
func (m *MockAerospikeClient) CreateComplexIndex(policy *aerospike.WritePolicy, namespace, set, indexName, binName string, indexType aerospike.IndexType, indexCollectionType aerospike.IndexCollectionType, ctx ...*aerospike.CDTContext) (*aerospike.IndexTask, aerospike.Error) {
	m.ctrl.T.Helper()
	varargs := []any{policy, namespace, set, indexName, binName, indexType, indexCollectionType}
	for _, a := range ctx {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateComplexIndex", varargs...)
	ret0, _ := ret[0].(*aerospike.IndexTask)
	ret1, _ := ret[1].(aerospike.Error)
	return ret0, ret1
}

// CreateComplexIndex indicates an expected call of CreateComplexIndex.
func (mr *MockAerospikeClientMockRecorder) CreateComplexIndex(policy, namespace, set, indexName, binName, indexType, indexCollectionType any, ctx ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{policy, namespace, set, indexName, binName, indexType, indexCollectionType}, ctx...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateComplexIndex", reflect.TypeOf((*MockAerospikeClient)(nil).CreateComplexIndex), varargs...)
}

// CreateIndexWithExpression mocks base method.
func (m *MockAerospikeClient) CreateIndexWithExpression(policy *aerospike.WritePolicy, namespace, set, indexName string, indexType aerospike.IndexType, indexCollectionType aerospike.IndexCollectionType, expression *aerospike.Expression) (*aerospike.IndexTask, aerospike.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIndexWithExpression", policy, namespace, set, indexName, indexType, indexCollectionType, expression)
	ret0, _ := ret[0].(*aerospike.IndexTask)
	ret1, _ := ret[1].(aerospike.Error)
	return ret0, ret1
}

// CreateIndexWithExpression indicates an expected call of CreateIndexWithExpression.
func (mr *MockAerospikeClientMockRecorder) CreateIndexWithExpression(policy, namespace, set, indexName, indexType, indexCollectionType, expression any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIndexWithExpression", reflect.TypeOf((*MockAerospikeClient)(nil).CreateIndexWithExpression), policy, namespace, set, indexName, indexType, indexCollectionType, expression)
}

// DropIndex mocks base method.
func (m *MockAerospikeClient) DropIndex(policy *aerospike.WritePolicy, namespace, set, indexName string) aerospike.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DropIndex", policy, namespace, set, indexName)
	ret0, _ := ret[0].(aerospike.Error)
	return ret0
}

// DropIndex indicates an expected call of DropIndex.
func (mr *MockAerospikeClientMockRecorder) DropIndex(policy, namespace, set, indexName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DropIndex", reflect.TypeOf((*MockAerospikeClient)(nil).DropIndex), policy, namespace, set, indexName)
}

// GetDefaultInfoPolicy mocks base method.
func (m *MockAerospikeClient) GetDefaultInfoPolicy() *aerospike.InfoPolicy {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultInfoPolicy")
	ret0, _ := ret[0].(*aerospike.InfoPolicy)
	return ret0
}

// GetDefaultInfoPolicy indicates an expected call of GetDefaultInfoPolicy.
func (mr *MockAerospikeClientMockRecorder) GetDefaultInfoPolicy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultInfoPolicy", reflect.TypeOf((*MockAerospikeClient)(nil).GetDefaultInfoPolicy))
}

// GetDefaultScanPolicy mocks base method.
func (m *MockAerospikeClient) GetDefaultScanPolicy() *aerospike.ScanPolicy {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultScanPolicy")
	ret0, _ := ret[0].(*aerospike.ScanPolicy)
	return ret0
}

// GetDefaultScanPolicy indicates an expected call of GetDefaultScanPolicy.
func (mr *MockAerospikeClientMockRecorder) GetDefaultScanPolicy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultScanPolicy", reflect.TypeOf((*MockAerospikeClient)(nil).GetDefaultScanPolicy))
}

// GetDefaultWritePolicy mocks base method.
func (m *MockAerospikeClient) GetDefaultWritePolicy() *aerospike.WritePolicy {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultWritePolicy")
	ret0, _ := ret[0].(*aerospike.WritePolicy)
	return ret0
}

// GetDefaultWritePolicy indicates an expected call of GetDefaultWritePolicy.
func (mr *MockAerospikeClientMockRecorder) GetDefaultWritePolicy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultWritePolicy", reflect.TypeOf((*MockAerospikeClient)(nil).GetDefaultWritePolicy))
}

// GetNodes mocks base method.
func (m *MockAerospikeClient) GetNodes() []*aerospike.Node {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodes")
	ret0, _ := ret[0].([]*aerospike.Node)
	return ret0
}

// GetNodes indicates an expected call of GetNodes.
func (mr *MockAerospikeClientMockRecorder) GetNodes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodes", reflect.TypeOf((*MockAerospikeClient)(nil).GetNodes))
}

// Put mocks base method.
func (m *MockAerospikeClient) Put(policy *aerospike.WritePolicy, key *aerospike.Key, bins aerospike.BinMap) aerospike.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", policy, key, bins)
	ret0, _ := ret[0].(aerospike.Error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockAerospikeClientMockRecorder) Put(policy, key, bins any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockAerospikeClient)(nil).Put), policy, key, bins)
}

// PutPayload mocks base method.
func (m *MockAerospikeClient) PutPayload(policy *aerospike.WritePolicy, key *aerospike.Key, payload []byte) aerospike.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutPayload", policy, key, payload)
	ret0, _ := ret[0].(aerospike.Error)
	return ret0
}

// PutPayload indicates an expected call of PutPayload.
func (mr *MockAerospikeClientMockRecorder) PutPayload(policy, key, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutPayload", reflect.TypeOf((*MockAerospikeClient)(nil).PutPayload), policy, key, payload)
}

// RegisterUDF mocks base method.
func (m *MockAerospikeClient) RegisterUDF(policy *aerospike.WritePolicy, udfBody []byte, serverPath string, language aerospike.Language) (*aerospike.RegisterTask, aerospike.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterUDF", policy, udfBody, serverPath, language)
	ret0, _ := ret[0].(*aerospike.RegisterTask)
	ret1, _ := ret[1].(aerospike.Error)
	return ret0, ret1
}

// RegisterUDF indicates an expected call of RegisterUDF.
func (mr *MockAerospikeClientMockRecorder) RegisterUDF(policy, udfBody, serverPath, language any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUDF", reflect.TypeOf((*MockAerospikeClient)(nil).RegisterUDF), policy, udfBody, serverPath, language)
}

// ScanNode mocks base method.
func (m *MockAerospikeClient) ScanNode(scanPolicy *aerospike.ScanPolicy, node *aerospike.Node, namespace, setName string, binNames ...string) (*aerospike.Recordset, aerospike.Error) {
	m.ctrl.T.Helper()
	varargs := []any{scanPolicy, node, namespace, setName}
	for _, a := range binNames {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ScanNode", varargs...)
	ret0, _ := ret[0].(*aerospike.Recordset)
	ret1, _ := ret[1].(aerospike.Error)
	return ret0, ret1
}

// ScanNode indicates an expected call of ScanNode.
func (mr *MockAerospikeClientMockRecorder) ScanNode(scanPolicy, node, namespace, setName any, binNames ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{scanPolicy, node, namespace, setName}, binNames...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScanNode", reflect.TypeOf((*MockAerospikeClient)(nil).ScanNode), varargs...)
}

// ScanPartitions mocks base method.
func (m *MockAerospikeClient) ScanPartitions(scanPolicy *aerospike.ScanPolicy, partitionFilter *aerospike.PartitionFilter, namespace, setName string, binNames ...string) (*aerospike.Recordset, aerospike.Error) {
	m.ctrl.T.Helper()
	varargs := []any{scanPolicy, partitionFilter, namespace, setName}
	for _, a := range binNames {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ScanPartitions", varargs...)
	ret0, _ := ret[0].(*aerospike.Recordset)
	ret1, _ := ret[1].(aerospike.Error)
	return ret0, ret1
}

// ScanPartitions indicates an expected call of ScanPartitions.
func (mr *MockAerospikeClientMockRecorder) ScanPartitions(scanPolicy, partitionFilter, namespace, setName any, binNames ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{scanPolicy, partitionFilter, namespace, setName}, binNames...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScanPartitions", reflect.TypeOf((*MockAerospikeClient)(nil).ScanPartitions), varargs...)
}
