// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aerospike/aerospike-backup-service/v3/pkg/service/aerospike (interfaces: ClientManager,NamespaceValidator,Client,ClientFactory)
//
// Generated by this command:
//
//	mockgen -package aerospike -destination /Users/ak/work/aerospike-backup-service/pkg/service/aerospike/mockgen.go github.com/aerospike/aerospike-backup-service/v3/pkg/service/aerospike ClientManager,NamespaceValidator,Client,ClientFactory
//

// Package aerospike is a generated GoMock package.
package aerospike

import (
	context "context"
	slog "log/slog"
	reflect "reflect"

	model "github.com/aerospike/aerospike-backup-service/v3/pkg/model"
	backup "github.com/aerospike/backup-go"
	gomock "go.uber.org/mock/gomock"
)

// MockClientManager is a mock of ClientManager interface.
type MockClientManager struct {
	ctrl     *gomock.Controller
	recorder *MockClientManagerMockRecorder
	isgomock struct{}
}

// MockClientManagerMockRecorder is the mock recorder for MockClientManager.
type MockClientManagerMockRecorder struct {
	mock *MockClientManager
}

// NewMockClientManager creates a new mock instance.
func NewMockClientManager(ctrl *gomock.Controller) *MockClientManager {
	mock := &MockClientManager{ctrl: ctrl}
	mock.recorder = &MockClientManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientManager) EXPECT() *MockClientManagerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockClientManager) Close(arg0 Client) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close", arg0)
}

// Close indicates an expected call of Close.
func (mr *MockClientManagerMockRecorder) Close(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockClientManager)(nil).Close), arg0)
}

// GetClient mocks base method.
func (m *MockClientManager) GetClient(ctx context.Context, cluster *model.AerospikeCluster, logger *slog.Logger) (Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClient", ctx, cluster, logger)
	ret0, _ := ret[0].(Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClient indicates an expected call of GetClient.
func (mr *MockClientManagerMockRecorder) GetClient(ctx, cluster, logger any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClient", reflect.TypeOf((*MockClientManager)(nil).GetClient), ctx, cluster, logger)
}

// MockNamespaceValidator is a mock of NamespaceValidator interface.
type MockNamespaceValidator struct {
	ctrl     *gomock.Controller
	recorder *MockNamespaceValidatorMockRecorder
	isgomock struct{}
}

// MockNamespaceValidatorMockRecorder is the mock recorder for MockNamespaceValidator.
type MockNamespaceValidatorMockRecorder struct {
	mock *MockNamespaceValidator
}

// NewMockNamespaceValidator creates a new mock instance.
func NewMockNamespaceValidator(ctrl *gomock.Controller) *MockNamespaceValidator {
	mock := &MockNamespaceValidator{ctrl: ctrl}
	mock.recorder = &MockNamespaceValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNamespaceValidator) EXPECT() *MockNamespaceValidatorMockRecorder {
	return m.recorder
}

// Validate mocks base method.
func (m *MockNamespaceValidator) Validate(ctx context.Context, cfg *model.Config) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Validate", ctx, cfg)
}

// Validate indicates an expected call of Validate.
func (mr *MockNamespaceValidatorMockRecorder) Validate(ctx, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockNamespaceValidator)(nil).Validate), ctx, cfg)
}

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// AerospikeClient mocks base method.
func (m *MockClient) AerospikeClient() backup.AerospikeClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AerospikeClient")
	ret0, _ := ret[0].(backup.AerospikeClient)
	return ret0
}

// AerospikeClient indicates an expected call of AerospikeClient.
func (mr *MockClientMockRecorder) AerospikeClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AerospikeClient", reflect.TypeOf((*MockClient)(nil).AerospikeClient))
}

// Backup mocks base method.
func (m *MockClient) Backup(ctx context.Context, config *backup.ConfigBackup, writer backup.Writer, reader backup.StreamingReader) (*backup.BackupHandler, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Backup", ctx, config, writer, reader)
	ret0, _ := ret[0].(*backup.BackupHandler)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Backup indicates an expected call of Backup.
func (mr *MockClientMockRecorder) Backup(ctx, config, writer, reader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Backup", reflect.TypeOf((*MockClient)(nil).Backup), ctx, config, writer, reader)
}

// BackupXDR mocks base method.
func (m *MockClient) BackupXDR(ctx context.Context, config *backup.ConfigBackupXDR, writer backup.Writer) (*backup.HandlerBackupXDR, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BackupXDR", ctx, config, writer)
	ret0, _ := ret[0].(*backup.HandlerBackupXDR)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BackupXDR indicates an expected call of BackupXDR.
func (mr *MockClientMockRecorder) BackupXDR(ctx, config, writer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BackupXDR", reflect.TypeOf((*MockClient)(nil).BackupXDR), ctx, config, writer)
}

// InfoClient mocks base method.
func (m *MockClient) InfoClient() backup.InfoGetter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InfoClient")
	ret0, _ := ret[0].(backup.InfoGetter)
	return ret0
}

// InfoClient indicates an expected call of InfoClient.
func (mr *MockClientMockRecorder) InfoClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InfoClient", reflect.TypeOf((*MockClient)(nil).InfoClient))
}

// Restore mocks base method.
func (m *MockClient) Restore(ctx context.Context, config *backup.ConfigRestore, streamingReader backup.StreamingReader) (backup.Restorer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restore", ctx, config, streamingReader)
	ret0, _ := ret[0].(backup.Restorer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Restore indicates an expected call of Restore.
func (mr *MockClientMockRecorder) Restore(ctx, config, streamingReader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restore", reflect.TypeOf((*MockClient)(nil).Restore), ctx, config, streamingReader)
}

// MockClientFactory is a mock of ClientFactory interface.
type MockClientFactory struct {
	ctrl     *gomock.Controller
	recorder *MockClientFactoryMockRecorder
	isgomock struct{}
}

// MockClientFactoryMockRecorder is the mock recorder for MockClientFactory.
type MockClientFactoryMockRecorder struct {
	mock *MockClientFactory
}

// NewMockClientFactory creates a new mock instance.
func NewMockClientFactory(ctrl *gomock.Controller) *MockClientFactory {
	mock := &MockClientFactory{ctrl: ctrl}
	mock.recorder = &MockClientFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientFactory) EXPECT() *MockClientFactoryMockRecorder {
	return m.recorder
}

// NewBackupClient mocks base method.
func (m *MockClientFactory) NewBackupClient(arg0 backup.AerospikeClient, arg1 ...backup.ClientOpt) (Client, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewBackupClient", varargs...)
	ret0, _ := ret[0].(Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewBackupClient indicates an expected call of NewBackupClient.
func (mr *MockClientFactoryMockRecorder) NewBackupClient(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewBackupClient", reflect.TypeOf((*MockClientFactory)(nil).NewBackupClient), varargs...)
}

// NewClientWithPolicyAndHost mocks base method.
func (m *MockClientFactory) NewClientWithPolicyAndHost(arg0 *model.AerospikeCluster) (backup.AerospikeClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewClientWithPolicyAndHost", arg0)
	ret0, _ := ret[0].(backup.AerospikeClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewClientWithPolicyAndHost indicates an expected call of NewClientWithPolicyAndHost.
func (mr *MockClientFactoryMockRecorder) NewClientWithPolicyAndHost(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewClientWithPolicyAndHost", reflect.TypeOf((*MockClientFactory)(nil).NewClientWithPolicyAndHost), arg0)
}
