// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aerospike/aerospike-backup-service/v3/pkg/service/aerospike (interfaces: ClientManager,NamespaceValidator)
//
// Generated by this command:
//
//	mockgen -package aerospike -destination /Users/ak/work/aerospike-backup-service/pkg/service/aerospike/mockgen.go github.com/aerospike/aerospike-backup-service/v3/pkg/service/aerospike ClientManager,NamespaceValidator
//

// Package aerospike is a generated GoMock package.
package aerospike

import (
	reflect "reflect"

	model "github.com/aerospike/aerospike-backup-service/v3/pkg/model"
	backup "github.com/aerospike/backup-go"
	asinfo "github.com/aerospike/backup-go/pkg/asinfo"
	gomock "go.uber.org/mock/gomock"
)

// MockClientManager is a mock of ClientManager interface.
type MockClientManager struct {
	ctrl     *gomock.Controller
	recorder *MockClientManagerMockRecorder
	isgomock struct{}
}

// MockClientManagerMockRecorder is the mock recorder for MockClientManager.
type MockClientManagerMockRecorder struct {
	mock *MockClientManager
}

// NewMockClientManager creates a new mock instance.
func NewMockClientManager(ctrl *gomock.Controller) *MockClientManager {
	mock := &MockClientManager{ctrl: ctrl}
	mock.recorder = &MockClientManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientManager) EXPECT() *MockClientManagerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockClientManager) Close(arg0 *backup.Client) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close", arg0)
}

// Close indicates an expected call of Close.
func (mr *MockClientManagerMockRecorder) Close(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockClientManager)(nil).Close), arg0)
}

// GetClient mocks base method.
func (m *MockClientManager) GetClient(arg0 *model.AerospikeCluster) (*backup.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClient", arg0)
	ret0, _ := ret[0].(*backup.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClient indicates an expected call of GetClient.
func (mr *MockClientManagerMockRecorder) GetClient(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClient", reflect.TypeOf((*MockClientManager)(nil).GetClient), arg0)
}

// MockNamespaceValidator is a mock of NamespaceValidator interface.
type MockNamespaceValidator struct {
	ctrl     *gomock.Controller
	recorder *MockNamespaceValidatorMockRecorder
	isgomock struct{}
}

// MockNamespaceValidatorMockRecorder is the mock recorder for MockNamespaceValidator.
type MockNamespaceValidatorMockRecorder struct {
	mock *MockNamespaceValidator
}

// NewMockNamespaceValidator creates a new mock instance.
func NewMockNamespaceValidator(ctrl *gomock.Controller) *MockNamespaceValidator {
	mock := &MockNamespaceValidator{ctrl: ctrl}
	mock.recorder = &MockNamespaceValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNamespaceValidator) EXPECT() *MockNamespaceValidatorMockRecorder {
	return m.recorder
}

// GetAllNamespacesOfCluster mocks base method.
func (m *MockNamespaceValidator) GetAllNamespacesOfCluster(cluster asinfo.NodeGetter) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllNamespacesOfCluster", cluster)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllNamespacesOfCluster indicates an expected call of GetAllNamespacesOfCluster.
func (mr *MockNamespaceValidatorMockRecorder) GetAllNamespacesOfCluster(cluster any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllNamespacesOfCluster", reflect.TypeOf((*MockNamespaceValidator)(nil).GetAllNamespacesOfCluster), cluster)
}

// IsEmpty mocks base method.
func (m *MockNamespaceValidator) IsEmpty(client *backup.Client, namespace string, request *model.RestoreTimestampRequest) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEmpty", client, namespace, request)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsEmpty indicates an expected call of IsEmpty.
func (mr *MockNamespaceValidatorMockRecorder) IsEmpty(client, namespace, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEmpty", reflect.TypeOf((*MockNamespaceValidator)(nil).IsEmpty), client, namespace, request)
}

// MissingNamespaces mocks base method.
func (m *MockNamespaceValidator) MissingNamespaces(cluster *model.AerospikeCluster, namespaces []string) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MissingNamespaces", cluster, namespaces)
	ret0, _ := ret[0].([]string)
	return ret0
}

// MissingNamespaces indicates an expected call of MissingNamespaces.
func (mr *MockNamespaceValidatorMockRecorder) MissingNamespaces(cluster, namespaces any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MissingNamespaces", reflect.TypeOf((*MockNamespaceValidator)(nil).MissingNamespaces), cluster, namespaces)
}

// ValidateBackupRoutineNamespaces mocks base method.
func (m *MockNamespaceValidator) ValidateBackupRoutineNamespaces(routine *model.BackupRoutine) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateBackupRoutineNamespaces", routine)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateBackupRoutineNamespaces indicates an expected call of ValidateBackupRoutineNamespaces.
func (mr *MockNamespaceValidatorMockRecorder) ValidateBackupRoutineNamespaces(routine any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateBackupRoutineNamespaces", reflect.TypeOf((*MockNamespaceValidator)(nil).ValidateBackupRoutineNamespaces), routine)
}

// ValidateConfig mocks base method.
func (m *MockNamespaceValidator) ValidateConfig(configModel *model.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateConfig", configModel)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateConfig indicates an expected call of ValidateConfig.
func (mr *MockNamespaceValidatorMockRecorder) ValidateConfig(configModel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateConfig", reflect.TypeOf((*MockNamespaceValidator)(nil).ValidateConfig), configModel)
}

// ValidatePresent mocks base method.
func (m *MockNamespaceValidator) ValidatePresent(cluster *model.AerospikeCluster, ns ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{cluster}
	for _, a := range ns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ValidatePresent", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidatePresent indicates an expected call of ValidatePresent.
func (mr *MockNamespaceValidatorMockRecorder) ValidatePresent(cluster any, ns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{cluster}, ns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatePresent", reflect.TypeOf((*MockNamespaceValidator)(nil).ValidatePresent), varargs...)
}

// ValidateRoutines mocks base method.
func (m *MockNamespaceValidator) ValidateRoutines(cluster *model.AerospikeCluster, routines map[string]*model.BackupRoutine) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateRoutines", cluster, routines)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateRoutines indicates an expected call of ValidateRoutines.
func (mr *MockNamespaceValidatorMockRecorder) ValidateRoutines(cluster, routines any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateRoutines", reflect.TypeOf((*MockNamespaceValidator)(nil).ValidateRoutines), cluster, routines)
}
