// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aerospike/aerospike-backup-service/v3/pkg/service/aerospike (interfaces: ClientManager,Backuper,Restorer,Client,ClientFactory)
//
// Generated by this command:
//
//	mockgen -package aerospike -destination /Users/ak/work/aerospike-backup-service/pkg/service/aerospike/mockgen.go github.com/aerospike/aerospike-backup-service/v3/pkg/service/aerospike ClientManager,Backuper,Restorer,Client,ClientFactory
//

// Package aerospike is a generated GoMock package.
package aerospike

import (
	context "context"
	reflect "reflect"

	model "github.com/aerospike/aerospike-backup-service/v3/pkg/model"
	backup "github.com/aerospike/backup-go"
	gomock "go.uber.org/mock/gomock"
)

// MockClientManager is a mock of ClientManager interface.
type MockClientManager struct {
	ctrl     *gomock.Controller
	recorder *MockClientManagerMockRecorder
	isgomock struct{}
}

// MockClientManagerMockRecorder is the mock recorder for MockClientManager.
type MockClientManagerMockRecorder struct {
	mock *MockClientManager
}

// NewMockClientManager creates a new mock instance.
func NewMockClientManager(ctrl *gomock.Controller) *MockClientManager {
	mock := &MockClientManager{ctrl: ctrl}
	mock.recorder = &MockClientManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientManager) EXPECT() *MockClientManagerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockClientManager) Close(arg0 Client) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close", arg0)
}

// Close indicates an expected call of Close.
func (mr *MockClientManagerMockRecorder) Close(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockClientManager)(nil).Close), arg0)
}

// GetClient mocks base method.
func (m *MockClientManager) GetClient(arg0 *model.AerospikeCluster) (Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClient", arg0)
	ret0, _ := ret[0].(Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClient indicates an expected call of GetClient.
func (mr *MockClientManagerMockRecorder) GetClient(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClient", reflect.TypeOf((*MockClientManager)(nil).GetClient), arg0)
}

// MockBackuper is a mock of Backuper interface.
type MockBackuper struct {
	ctrl     *gomock.Controller
	recorder *MockBackuperMockRecorder
	isgomock struct{}
}

// MockBackuperMockRecorder is the mock recorder for MockBackuper.
type MockBackuperMockRecorder struct {
	mock *MockBackuper
}

// NewMockBackuper creates a new mock instance.
func NewMockBackuper(ctrl *gomock.Controller) *MockBackuper {
	mock := &MockBackuper{ctrl: ctrl}
	mock.recorder = &MockBackuperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackuper) EXPECT() *MockBackuperMockRecorder {
	return m.recorder
}

// Backup mocks base method.
func (m *MockBackuper) Backup(ctx context.Context, config *backup.ConfigBackup, writer backup.Writer, reader backup.StreamingReader) (*backup.BackupHandler, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Backup", ctx, config, writer, reader)
	ret0, _ := ret[0].(*backup.BackupHandler)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Backup indicates an expected call of Backup.
func (mr *MockBackuperMockRecorder) Backup(ctx, config, writer, reader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Backup", reflect.TypeOf((*MockBackuper)(nil).Backup), ctx, config, writer, reader)
}

// BackupXDR mocks base method.
func (m *MockBackuper) BackupXDR(ctx context.Context, config *backup.ConfigBackupXDR, writer backup.Writer) (*backup.HandlerBackupXDR, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BackupXDR", ctx, config, writer)
	ret0, _ := ret[0].(*backup.HandlerBackupXDR)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BackupXDR indicates an expected call of BackupXDR.
func (mr *MockBackuperMockRecorder) BackupXDR(ctx, config, writer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BackupXDR", reflect.TypeOf((*MockBackuper)(nil).BackupXDR), ctx, config, writer)
}

// InfoClient mocks base method.
func (m *MockBackuper) InfoClient() backup.InfoGetter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InfoClient")
	ret0, _ := ret[0].(backup.InfoGetter)
	return ret0
}

// InfoClient indicates an expected call of InfoClient.
func (mr *MockBackuperMockRecorder) InfoClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InfoClient", reflect.TypeOf((*MockBackuper)(nil).InfoClient))
}

// MockRestorer is a mock of Restorer interface.
type MockRestorer struct {
	ctrl     *gomock.Controller
	recorder *MockRestorerMockRecorder
	isgomock struct{}
}

// MockRestorerMockRecorder is the mock recorder for MockRestorer.
type MockRestorerMockRecorder struct {
	mock *MockRestorer
}

// NewMockRestorer creates a new mock instance.
func NewMockRestorer(ctrl *gomock.Controller) *MockRestorer {
	mock := &MockRestorer{ctrl: ctrl}
	mock.recorder = &MockRestorerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRestorer) EXPECT() *MockRestorerMockRecorder {
	return m.recorder
}

// InfoClient mocks base method.
func (m *MockRestorer) InfoClient() backup.InfoGetter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InfoClient")
	ret0, _ := ret[0].(backup.InfoGetter)
	return ret0
}

// InfoClient indicates an expected call of InfoClient.
func (mr *MockRestorerMockRecorder) InfoClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InfoClient", reflect.TypeOf((*MockRestorer)(nil).InfoClient))
}

// Restore mocks base method.
func (m *MockRestorer) Restore(ctx context.Context, config *backup.ConfigRestore, streamingReader backup.StreamingReader) (backup.Restorer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restore", ctx, config, streamingReader)
	ret0, _ := ret[0].(backup.Restorer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Restore indicates an expected call of Restore.
func (mr *MockRestorerMockRecorder) Restore(ctx, config, streamingReader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restore", reflect.TypeOf((*MockRestorer)(nil).Restore), ctx, config, streamingReader)
}

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// AerospikeClient mocks base method.
func (m *MockClient) AerospikeClient() backup.AerospikeClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AerospikeClient")
	ret0, _ := ret[0].(backup.AerospikeClient)
	return ret0
}

// AerospikeClient indicates an expected call of AerospikeClient.
func (mr *MockClientMockRecorder) AerospikeClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AerospikeClient", reflect.TypeOf((*MockClient)(nil).AerospikeClient))
}

// Backup mocks base method.
func (m *MockClient) Backup(ctx context.Context, config *backup.ConfigBackup, writer backup.Writer, reader backup.StreamingReader) (*backup.BackupHandler, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Backup", ctx, config, writer, reader)
	ret0, _ := ret[0].(*backup.BackupHandler)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Backup indicates an expected call of Backup.
func (mr *MockClientMockRecorder) Backup(ctx, config, writer, reader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Backup", reflect.TypeOf((*MockClient)(nil).Backup), ctx, config, writer, reader)
}

// BackupXDR mocks base method.
func (m *MockClient) BackupXDR(ctx context.Context, config *backup.ConfigBackupXDR, writer backup.Writer) (*backup.HandlerBackupXDR, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BackupXDR", ctx, config, writer)
	ret0, _ := ret[0].(*backup.HandlerBackupXDR)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BackupXDR indicates an expected call of BackupXDR.
func (mr *MockClientMockRecorder) BackupXDR(ctx, config, writer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BackupXDR", reflect.TypeOf((*MockClient)(nil).BackupXDR), ctx, config, writer)
}

// InfoClient mocks base method.
func (m *MockClient) InfoClient() backup.InfoGetter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InfoClient")
	ret0, _ := ret[0].(backup.InfoGetter)
	return ret0
}

// InfoClient indicates an expected call of InfoClient.
func (mr *MockClientMockRecorder) InfoClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InfoClient", reflect.TypeOf((*MockClient)(nil).InfoClient))
}

// Restore mocks base method.
func (m *MockClient) Restore(ctx context.Context, config *backup.ConfigRestore, streamingReader backup.StreamingReader) (backup.Restorer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restore", ctx, config, streamingReader)
	ret0, _ := ret[0].(backup.Restorer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Restore indicates an expected call of Restore.
func (mr *MockClientMockRecorder) Restore(ctx, config, streamingReader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restore", reflect.TypeOf((*MockClient)(nil).Restore), ctx, config, streamingReader)
}

// MockClientFactory is a mock of ClientFactory interface.
type MockClientFactory struct {
	ctrl     *gomock.Controller
	recorder *MockClientFactoryMockRecorder
	isgomock struct{}
}

// MockClientFactoryMockRecorder is the mock recorder for MockClientFactory.
type MockClientFactoryMockRecorder struct {
	mock *MockClientFactory
}

// NewMockClientFactory creates a new mock instance.
func NewMockClientFactory(ctrl *gomock.Controller) *MockClientFactory {
	mock := &MockClientFactory{ctrl: ctrl}
	mock.recorder = &MockClientFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientFactory) EXPECT() *MockClientFactoryMockRecorder {
	return m.recorder
}

// IsClusterHealthy mocks base method.
func (m *MockClientFactory) IsClusterHealthy(client Cluster) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsClusterHealthy", client)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsClusterHealthy indicates an expected call of IsClusterHealthy.
func (mr *MockClientFactoryMockRecorder) IsClusterHealthy(client any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsClusterHealthy", reflect.TypeOf((*MockClientFactory)(nil).IsClusterHealthy), client)
}

// NewBackupClient mocks base method.
func (m *MockClientFactory) NewBackupClient(arg0 backup.AerospikeClient, arg1 ...backup.ClientOpt) (Client, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewBackupClient", varargs...)
	ret0, _ := ret[0].(Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewBackupClient indicates an expected call of NewBackupClient.
func (mr *MockClientFactoryMockRecorder) NewBackupClient(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewBackupClient", reflect.TypeOf((*MockClientFactory)(nil).NewBackupClient), varargs...)
}

// NewClientWithPolicyAndHost mocks base method.
func (m *MockClientFactory) NewClientWithPolicyAndHost(arg0 *model.AerospikeCluster) (backup.AerospikeClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewClientWithPolicyAndHost", arg0)
	ret0, _ := ret[0].(backup.AerospikeClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewClientWithPolicyAndHost indicates an expected call of NewClientWithPolicyAndHost.
func (mr *MockClientFactoryMockRecorder) NewClientWithPolicyAndHost(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewClientWithPolicyAndHost", reflect.TypeOf((*MockClientFactory)(nil).NewClientWithPolicyAndHost), arg0)
}
