// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aerospike/backup-go (interfaces: Writer)
//
// Generated by this command:
//
//	mockgen -package backupexecutor -destination pkg/service/backupexecutor/backupgo_mockgen.go github.com/aerospike/backup-go Writer
//

// Package backupexecutor is a generated GoMock package.
package backupexecutor

import (
	context "context"
	io "io"
	reflect "reflect"

	options "github.com/aerospike/backup-go/io/storage/options"
	gomock "go.uber.org/mock/gomock"
)

// MockWriter is a mock of Writer interface.
type MockWriter struct {
	ctrl     *gomock.Controller
	recorder *MockWriterMockRecorder
	isgomock struct{}
}

// MockWriterMockRecorder is the mock recorder for MockWriter.
type MockWriterMockRecorder struct {
	mock *MockWriter
}

// NewMockWriter creates a new mock instance.
func NewMockWriter(ctrl *gomock.Controller) *MockWriter {
	mock := &MockWriter{ctrl: ctrl}
	mock.recorder = &MockWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWriter) EXPECT() *MockWriterMockRecorder {
	return m.recorder
}

// GetOptions mocks base method.
func (m *MockWriter) GetOptions() options.Options {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOptions")
	ret0, _ := ret[0].(options.Options)
	return ret0
}

// GetOptions indicates an expected call of GetOptions.
func (mr *MockWriterMockRecorder) GetOptions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOptions", reflect.TypeOf((*MockWriter)(nil).GetOptions))
}

// GetType mocks base method.
func (m *MockWriter) GetType() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetType")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetType indicates an expected call of GetType.
func (mr *MockWriterMockRecorder) GetType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetType", reflect.TypeOf((*MockWriter)(nil).GetType))
}

// NewWriter mocks base method.
func (m *MockWriter) NewWriter(ctx context.Context, filename string) (io.WriteCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewWriter", ctx, filename)
	ret0, _ := ret[0].(io.WriteCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewWriter indicates an expected call of NewWriter.
func (mr *MockWriterMockRecorder) NewWriter(ctx, filename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewWriter", reflect.TypeOf((*MockWriter)(nil).NewWriter), ctx, filename)
}

// Remove mocks base method.
func (m *MockWriter) Remove(ctx context.Context, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockWriterMockRecorder) Remove(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockWriter)(nil).Remove), ctx, path)
}

// RemoveFiles mocks base method.
func (m *MockWriter) RemoveFiles(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFiles", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFiles indicates an expected call of RemoveFiles.
func (mr *MockWriterMockRecorder) RemoveFiles(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFiles", reflect.TypeOf((*MockWriter)(nil).RemoveFiles), ctx)
}
