// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aerospike/aerospike-backup-service/v3/pkg/service/backupexecutor (interfaces: Backup,BackupHandler)
//
// Generated by this command:
//
//	mockgen -package backupexecutor -destination pkg/service/backupexecutor/mockgen.go github.com/aerospike/aerospike-backup-service/v3/pkg/service/backupexecutor Backup,BackupHandler
//

// Package backupexecutor is a generated GoMock package.
package backupexecutor

import (
	context "context"
	reflect "reflect"

	model "github.com/aerospike/aerospike-backup-service/v3/pkg/model"
	models "github.com/aerospike/backup-go/models"
	gomock "go.uber.org/mock/gomock"
)

// MockBackup is a mock of Backup interface.
type MockBackup struct {
	ctrl     *gomock.Controller
	recorder *MockBackupMockRecorder
	isgomock struct{}
}

// MockBackupMockRecorder is the mock recorder for MockBackup.
type MockBackupMockRecorder struct {
	mock *MockBackup
}

// NewMockBackup creates a new mock instance.
func NewMockBackup(ctrl *gomock.Controller) *MockBackup {
	mock := &MockBackup{ctrl: ctrl}
	mock.recorder = &MockBackupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackup) EXPECT() *MockBackupMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockBackup) Run(ctx context.Context, routine *model.BackupRoutine, timeBounds model.TimeBounds, namespace, path string) (BackupHandler, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, routine, timeBounds, namespace, path)
	ret0, _ := ret[0].(BackupHandler)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockBackupMockRecorder) Run(ctx, routine, timeBounds, namespace, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockBackup)(nil).Run), ctx, routine, timeBounds, namespace, path)
}

// MockBackupHandler is a mock of BackupHandler interface.
type MockBackupHandler struct {
	ctrl     *gomock.Controller
	recorder *MockBackupHandlerMockRecorder
	isgomock struct{}
}

// MockBackupHandlerMockRecorder is the mock recorder for MockBackupHandler.
type MockBackupHandlerMockRecorder struct {
	mock *MockBackupHandler
}

// NewMockBackupHandler creates a new mock instance.
func NewMockBackupHandler(ctrl *gomock.Controller) *MockBackupHandler {
	mock := &MockBackupHandler{ctrl: ctrl}
	mock.recorder = &MockBackupHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackupHandler) EXPECT() *MockBackupHandlerMockRecorder {
	return m.recorder
}

// GetMetrics mocks base method.
func (m *MockBackupHandler) GetMetrics() *models.Metrics {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetrics")
	ret0, _ := ret[0].(*models.Metrics)
	return ret0
}

// GetMetrics indicates an expected call of GetMetrics.
func (mr *MockBackupHandlerMockRecorder) GetMetrics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetrics", reflect.TypeOf((*MockBackupHandler)(nil).GetMetrics))
}

// GetStats mocks base method.
func (m *MockBackupHandler) GetStats() *models.BackupStats {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats")
	ret0, _ := ret[0].(*models.BackupStats)
	return ret0
}

// GetStats indicates an expected call of GetStats.
func (mr *MockBackupHandlerMockRecorder) GetStats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockBackupHandler)(nil).GetStats))
}

// Wait mocks base method.
func (m *MockBackupHandler) Wait(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Wait", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Wait indicates an expected call of Wait.
func (mr *MockBackupHandlerMockRecorder) Wait(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wait", reflect.TypeOf((*MockBackupHandler)(nil).Wait), arg0)
}
