apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aerospike-backup-service
  name: aerospike-backup-service
  namespace: aerospike
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aerospike-backup-service
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-template-psw.txt: |
          {{- with secret "secret/abs" -}}
          {{ .Data.data.password | base64Decode }}
          {{- end -}}
        vault.hashicorp.com/agent-inject-template-rootca.pem: |
          {{- with secret "secret/abs" -}}
          {{ .Data.data.rootCA_pem | base64Decode }}
          {{- end -}}
        vault.hashicorp.com/role: vault-role
        vault.hashicorp.com/secret-volume-path-psw.txt: /etc/aerospike-backup-service
        vault.hashicorp.com/secret-volume-path-rootca.pem: /etc/aerospike-backup-service/ssl
        vault.hashicorp.com/tls-skip-verify: "true"
      labels:
        app: aerospike-backup-service
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - aerospike-backup-service
              topologyKey: kubernetes.io/hostname
      automountServiceAccountToken: true
      containers:
        - name: aerospike-backup-service
          image: aerospike.jfrog.io/ecosystem-container-prod-local/aerospike-backup-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /etc/aerospike-backup-service/aerospike-backup-service.yml
              mountPropagation: None
              name: backup-config
              subPath: aerospike-backup-service.yml
      restartPolicy: Always
      serviceAccountName: backup-service
      volumes:
        - configMap:
            name: aerospike-backup-service-cm
            optional: true
          name: backup-config
