---
aerospike-clusters:
  cluster1:
    host: "localhost"
    port: 3000
    # user: "tester"
    # password: "psw"

storage:
  local1:
    type: 0
    path: "./testout"

backup-policies:
  policy1:
    type: 1
    parallel: 1
    remove-files: false

backup-routines:
  routine1:
    interval: 30000
    incr-interval: 5000
    backup-policy: "policy1"
    source-cluster: "cluster1"
    storage: "local1"
    namespace: "test"
    set-list:
      - set1
