---
aerospike-clusters:
  cluster1:
    seed-nodes:
      - host-name: "localhost"
        port: 3000
    # credentials:
      # user: "tester"
      # password: "psw"

storage:
  local1:
    type: "local"
    path: "./testout"

backup-policies:
  policy1:
    parallel: 1
    remove-files: KeepAll

backup-routines:
  routine1:
    interval-cron: "1/30 * * * * *" # every 30 seconds
    incr-interval-cron: "1/5 * * * * *" # every 5 seconds
    backup-policy: "policy1"
    source-cluster: "cluster1"
    storage: "local1"
    namespaces: ["test"]
    set-list:
      - set1
