service:
    logger:
        level: INFO
        file-writer:
            filename: log/backup-service.log
            maxsize: 0
            maxage: 0
            maxbackups: 0
            compress: false
aerospike-clusters:
    absDefaultCluster:
        seed-nodes:
            - host-name: localhost
              port: 3000
        credentials:
            user: tester
            password: psw
        max-parallel-scans: 5
storage:
    local:
        s3-storage:
            bucket: as-backup-bucket
            path: storage2
            s3-region: eu-central-1
            s3-profile: minio
            s3-endpoint-override: http://localhost:9000
    minio:
        s3-storage:
            bucket: as-backup-bucket
            path: storage1
            s3-region: eu-central-1
            s3-profile: minio
            s3-endpoint-override: http://localhost:9000
backup-policies:
    encryptedCompressedPolicy128:
        parallel: 8
        encryption:
            mode: AES128
            key-file: encryptionKey
        compression:
            mode: ZSTD
            level: 20
        sealed: true
    encryptedCompressedPolicy256:
        parallel: 8
        encryption:
            mode: AES256
            key-file: encryptionKey
        compression:
            mode: ZSTD
            level: 20
        sealed: true
    keepFilesMaxRecordsPolicy:
        parallel: 8
        sealed: true
    keepFilesPolicy:
        parallel: 8
        sealed: true
    keepFilesPolicySlow:
        parallel: 8
        bandwidth: 1
        sealed: true
    noIndexesUdfsRecords:
        parallel: 8
        no-records: true
        no-indexes: true
        no-udfs: true
        sealed: true
    notSealed:
        parallel: 8
        sealed: false
    removeFilesPolicy:
        parallel: 8
        retention:
            full: 1
            incremental: 0
        sealed: true
    removeIncrementalPolicy:
        parallel: 8
        retention:
            incremental: 0
        sealed: true
    xdrBackup:
        parallel: 8
        xdr:
            local-host: host.docker.internal
backup-routines:
    edgeCases:
        backup-policy: keepFilesPolicy
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '@yearly'
        namespaces:
            - source-ns7
    everySecondBackup:
        backup-policy: keepFilesPolicy
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '* * * * * *'
        namespaces:
            - source-ns20
        disabled: true
    filterBySetAndBin:
        backup-policy: removeFilesPolicy
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '@yearly'
        namespaces:
            - source-ns8
        set-list:
            - backupSet
        bin-list:
            - backupBin
    fullBackup1:
        backup-policy: keepFilesPolicy
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '@yearly'
        namespaces:
            - source-ns9
    fullBackup2:
        backup-policy: keepFilesPolicy
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '@yearly'
        namespaces:
            - source-ns11
    fullBackup3:
        backup-policy: keepFilesPolicy
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '@yearly'
        namespaces:
            - source-ns12
    fullBackup3Namespaces:
        backup-policy: keepFilesPolicy
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '@yearly'
        namespaces:
            - source-ns15
            - source-ns16
            - source-ns17
    fullBackupEncrypedCompressed128:
        backup-policy: encryptedCompressedPolicy128
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '@yearly'
        namespaces:
            - source-ns18
    fullBackupEncrypedCompressed256:
        backup-policy: encryptedCompressedPolicy256
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '@yearly'
        namespaces:
            - source-ns21
    fullBackupFullCluster:
        backup-policy: keepFilesPolicy
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '@yearly'
    fullBackupSlow:
        backup-policy: keepFilesPolicySlow
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '@yearly'
        namespaces:
            - source-ns13
    incrementalBackupCluster:
        backup-policy: keepFilesPolicy
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '@yearly'
        incr-interval-cron: '*/10 * * * * *'
    incrementalBackupClusterNotSealed:
        backup-policy: notSealed
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '@yearly'
        incr-interval-cron: '*/10 * * * * *'
    incrementalBackupMultipleNSs:
        backup-policy: keepFilesPolicy
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '@yearly'
        incr-interval-cron: '*/10 * * * * *'
        namespaces:
            - source-ns18
            - source-ns19
            - source-ns20
    localStorage:
        backup-policy: keepFilesPolicy
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '@yearly'
        namespaces:
            - source-ns2
    localStorageIncremental1:
        backup-policy: keepFilesPolicy
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '@yearly'
        incr-interval-cron: '*/10 * * * * *'
        namespaces:
            - source-ns5
        set-list:
            - absSet5
    localStorageIncremental3:
        backup-policy: removeFilesPolicy
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '@yearly'
        incr-interval-cron: '*/10 * * * * *'
        namespaces:
            - source-ns10
    localStorageNotSealed:
        backup-policy: notSealed
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '@yearly'
        namespaces:
            - source-ns2
    localStorageRemoveFiles:
        backup-policy: removeFilesPolicy
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '@yearly'
        namespaces:
            - source-ns1
    minio:
        backup-policy: keepFilesMaxRecordsPolicy
        source-cluster: absDefaultCluster
        storage: minio
        interval-cron: '@yearly'
        namespaces:
            - source-ns4
    minioIncremental:
        backup-policy: removeIncrementalPolicy
        source-cluster: absDefaultCluster
        storage: minio
        interval-cron: '@yearly'
        incr-interval-cron: '*/10 * * * * *'
        namespaces:
            - source-ns6
        set-list:
            - absSet6
    minioRemoveFiles:
        backup-policy: removeFilesPolicy
        source-cluster: absDefaultCluster
        storage: minio
        interval-cron: '@yearly'
        namespaces:
            - source-ns3
    noIndexesUdfsRecords:
        backup-policy: noIndexesUdfsRecords
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '@yearly'
        namespaces:
            - source-ns19
    oneMinuteIntervalBackup:
        backup-policy: removeFilesPolicy
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: 0 */1 * * * *
        namespaces:
            - source-ns20
    timestamp:
        backup-policy: keepFilesPolicy
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '@yearly'
        incr-interval-cron: '*/9 * * * * *'
        namespaces:
            - source-ns14
    xdrBackup:
        backup-policy: xdrBackup
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '@yearly'
        incr-interval-cron: 0 */1 * * * *
        namespaces:
            - source-ns21
