# yaml-language-server: $schema=https://raw.githubusercontent.com/aerospike/aerospike-backup-service/refs/tags/v3.5.0/docs/config.schema.json
service:
    logger:
        level: INFO
        file-writer:
            filename: log/backup-service.log
            maxsize: 0
            maxage: 0
            maxbackups: 0
            compress: false
    backup:
        timestamp-format: EU
aerospike-clusters:
    absDefaultCluster:
        seed-nodes:
            - host-name: localhost
              port: 3100
        credentials:
            user: tester
            password: psw
        max-parallel-scans: 20
storage:
    local:
        local-storage:
            path: ./localStorage
    minio:
        s3-storage:
            bucket: as-backup-bucket
            path: storage1
            s3-region: eu-central-1
            s3-profile: minio
            s3-endpoint-override: http://localhost:9000
backup-policies:
    defaultPolicy:
        parallel: 8
        max-concurrent-nodes:
        retry-policy:
            base-timeout: 3000
            multiplier: 1
            max-retries: 10
        retention:
            full: 10
            incremental: 10
    encryptedCompressedPolicy128:
        parallel: 1
        retention:
            full: 1
            incremental: 0
        file-limit: 1
        encryption:
            mode: AES128
            key-file: encryptionKey
        compression:
            mode: ZSTD
            level: 20
    encryptedCompressedPolicy256:
        parallel: 8
        retention:
            full: 1
            incremental: 0
        encryption:
            mode: AES256
            key-env: BACKUP_ENCRYPTION_KEY
        compression:
            mode: ZSTD
            level: 10
    noIndexesUdfsRecords:
        parallel: 8
        retention:
            full: 10
        no-records: true
        no-indexes: true
        no-udfs: true
        with-cluster-configuration: true
    removeFilesPolicy:
        parallel: 8
        retention:
            full: 1
            incremental: 0
    sealed:
        parallel: 8
        retention:
            full: 10
            incremental: 10
        sealed: true
    withBandwidthLimit:
        parallel: 16
        parallel-write: 8
        socket-timeout: 60000
        total-timeout: 0
        retry-policy:
            base-timeout: 1000
            multiplier: 1
            max-retries: 1
        retention:
            full: 10
            incremental: 10
        no-records: false
        no-indexes: false
        no-udfs: false
        with-cluster-configuration: false
        bandwidth: 10
        file-limit: 250
        sealed: false
    withClusterConfiguration:
        retention:
            full: 10
        with-cluster-configuration: true
    withFileLimit:
        parallel: 1
        retry-policy:
            base-timeout: 1000
            multiplier: 1
            max-retries: 1
        retention:
            full: 10
            incremental: 10
        file-limit: 1
backup-routines:
    fullBackupSlow:
        backup-policy: withBandwidthLimit
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '@yearly'
        namespaces:
            - source-ns1
