# yaml-language-server: $schema=https://raw.githubusercontent.com/aerospike/aerospike-backup-service/refs/tags/v3.6.1/docs/config.schema.json
service:
    logger:
        level: INFO
        file-writer:
            filename: log/backup-service.log
            maxsize: 0
            maxage: 0
            maxbackups: 0
            compress: false
    backup:
        timestamp-format: EU
aerospike-clusters:
    absDefaultCluster:
        seed-nodes:
            - host-name: localhost
              port: 3100
        credentials:
            user: tester
            password: psw
        max-parallel-scans: 20
        use-services-alternate: true
storage:
    local:
        local-storage:
            path: ./localStorage
    minio:
        s3-storage:
            bucket: as-backup-bucket
            path: storage1
            s3-region: eu-central-1
            s3-profile: minio
            s3-endpoint-override: http://localhost:9000
backup-policies:
    defaultPolicy:
        parallel: 8
        retry-policy:
            base-timeout: 3000
            multiplier: 1
            max-retries: 10
        retention:
            full: 10
            incremental: 10
        compact: true
    encryptedCompressedPolicy128:
        parallel: 1
        retention:
            full: 1
            incremental: 0
        file-limit: 1
        encryption:
            mode: AES128
            key-file: encryptionKey
        compression:
            mode: ZSTD
            level: 20
    encryptedCompressedPolicy256:
        parallel: 8
        retention:
            full: 1
            incremental: 0
        encryption:
            mode: AES256
            key-env: BACKUP_ENCRYPTION_KEY
        compression:
            mode: ZSTD
            level: 10
    noIndexesUdfsRecords:
        parallel: 8
        retention:
            full: 10
        no-records: true
        no-indexes: true
        no-udfs: true
        with-cluster-configuration: true
    removeFilesPolicy:
        parallel: 8
        retention:
            full: 1
            incremental: 0
    sealed:
        parallel: 8
        retention:
            full: 10
            incremental: 10
        sealed: true
    withBandwidthLimit:
        parallel: 1
        retry-policy:
            base-timeout: 1000
            multiplier: 1
            max-retries: 1
        retention:
            full: 10
            incremental: 10
        bandwidth: 10
    withClusterConfiguration:
        retention:
            full: 10
        with-cluster-configuration: true
    withFileLimit:
        parallel: 1
        retry-policy:
            base-timeout: 1000
            multiplier: 1
            max-retries: 1
        retention:
            full: 10
            incremental: 10
        file-limit: 1
backup-routines:
    edgeCases:
        backup-policy: defaultPolicy
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '@yearly'
        namespaces:
            - source-ns7
    everySecondBackup:
        backup-policy: defaultPolicy
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '* * * * * *'
        namespaces:
            - source-ns20
        disabled: true
    filterBySetAndBin:
        backup-policy: defaultPolicy
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '@yearly'
        namespaces:
            - source-ns8
        set-list:
            - backupSet
        bin-list:
            - backupBin
    fullBackup1:
        backup-policy: defaultPolicy
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '@yearly'
        namespaces:
            - source-ns9
    fullBackup2:
        backup-policy: withFileLimit
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '@yearly'
        namespaces:
            - source-ns11
    fullBackup3:
        backup-policy: defaultPolicy
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '@yearly'
        namespaces:
            - source-ns12
    fullBackup3Namespaces:
        backup-policy: defaultPolicy
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '@yearly'
        namespaces:
            - source-ns15
            - source-ns16
            - source-ns17
    fullBackupEncrypedCompressed256:
        backup-policy: encryptedCompressedPolicy256
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '@yearly'
        namespaces:
            - source-ns21
    fullBackupEncryptedCompressed128:
        backup-policy: encryptedCompressedPolicy128
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '@yearly'
        namespaces:
            - source-ns18
    fullBackupFullCluster:
        backup-policy: defaultPolicy
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '@yearly'
        namespaces: []
    fullBackupSlow:
        backup-policy: withBandwidthLimit
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '@yearly'
        namespaces:
            - source-ns13
    incrementalBackupCluster:
        backup-policy: defaultPolicy
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '@yearly'
        incr-interval-cron: '*/10 * * * * *'
        namespaces: []
    incrementalBackupClusterSealed:
        backup-policy: sealed
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '@yearly'
        incr-interval-cron: '*/10 * * * * *'
        namespaces: []
    incrementalBackupEncryptedCompressed128:
        backup-policy: encryptedCompressedPolicy128
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '@yearly'
        incr-interval-cron: '*/10 * * * * *'
        namespaces:
            - source-ns23
    incrementalBackupMultipleNSs:
        backup-policy: defaultPolicy
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '@yearly'
        incr-interval-cron: '*/10 * * * * *'
        namespaces:
            - source-ns18
            - source-ns19
            - source-ns20
    localStorage:
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '@yearly'
        namespaces:
            - source-ns2
    localStorageIncremental1:
        backup-policy: defaultPolicy
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '@yearly'
        incr-interval-cron: '*/10 * * * * *'
        namespaces:
            - source-ns5
        set-list:
            - absSet5
    localStorageIncremental3:
        backup-policy: defaultPolicy
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '@yearly'
        incr-interval-cron: '*/10 * * * * *'
        namespaces:
            - source-ns10
    localStorageSealed:
        backup-policy: sealed
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '@yearly'
        namespaces:
            - source-ns2
    minio:
        backup-policy: defaultPolicy
        source-cluster: absDefaultCluster
        storage: minio
        interval-cron: '@yearly'
        namespaces:
            - source-ns4
    noIndexesUdfsRecords:
        backup-policy: noIndexesUdfsRecords
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '@yearly'
        namespaces:
            - source-ns19
    oneMinuteIntervalBackup:
        backup-policy: defaultPolicy
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: 0 */1 * * * *
        namespaces:
            - source-ns20
    timestamp:
        backup-policy: defaultPolicy
        source-cluster: absDefaultCluster
        storage: local
        interval-cron: '@yearly'
        incr-interval-cron: '*/10 * * * * *'
        namespaces:
            - source-ns14
