aerospike-clusters:
  absCluster1:
    host: "localhost"
    port: 3000
    user: tester
    password: psw
storage:
  minioStorage:
    # Use 1 for S3 or compatible and 0 for local storage.
    type: 1
    # as-backup-bucket is expected to exist in MinIO.
    path: s3://as-backup-bucket/minioStorage
    s3-region: eu-central-1
    s3-profile: minio
    s3-endpoint-override: http://localhost:9000
backup-policies:
  keepFilesPolicy:
    # Run backup operations in a single thread.
    parallel: 1
    # Previous full backups are not deleted when a new one is created.
    remove-files: false
backup-routines:
  minioKeepFilesRoutine:
    # 24 hours interval for full backups.
    interval: 86400000
    # 1 hour interval for incremental backups.
    incr-interval: 3600000
    source-cluster: absCluster1
    storage: minioStorage
    namespace: source-ns1
    backup-policy: keepFilesPolicy