// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aerospike/aerospike-backup-service/v3/pkg/service/storage (interfaces: Operations)
//
// Generated by this command:
//
//	mockgen -package storage -destination pkg/service/storage/mockgen.go github.com/aerospike/aerospike-backup-service/v3/pkg/service/storage Operations
//

// Package storage is a generated GoMock package.
package storage

import (
	bytes "bytes"
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/aerospike/aerospike-backup-service/v3/pkg/model"
	backup "github.com/aerospike/backup-go"
	options "github.com/aerospike/backup-go/io/storage/options"
	gomock "go.uber.org/mock/gomock"
)

// MockOperations is a mock of Operations interface.
type MockOperations struct {
	ctrl     *gomock.Controller
	recorder *MockOperationsMockRecorder
	isgomock struct{}
}

// MockOperationsMockRecorder is the mock recorder for MockOperations.
type MockOperationsMockRecorder struct {
	mock *MockOperations
}

// NewMockOperations creates a new mock instance.
func NewMockOperations(ctrl *gomock.Controller) *MockOperations {
	mock := &MockOperations{ctrl: ctrl}
	mock.recorder = &MockOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOperations) EXPECT() *MockOperationsMockRecorder {
	return m.recorder
}

// CreateDirReader mocks base method.
func (m *MockOperations) CreateDirReader(ctx context.Context, storage model.Storage, path string, opts ...options.Opt) (backup.StreamingReader, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, storage, path}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateDirReader", varargs...)
	ret0, _ := ret[0].(backup.StreamingReader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDirReader indicates an expected call of CreateDirReader.
func (mr *MockOperationsMockRecorder) CreateDirReader(ctx, storage, path any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, storage, path}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDirReader", reflect.TypeOf((*MockOperations)(nil).CreateDirReader), varargs...)
}

// CreateDirWriter mocks base method.
func (m *MockOperations) CreateDirWriter(ctx context.Context, storage model.Storage, path string, opts ...options.Opt) (backup.Writer, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, storage, path}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateDirWriter", varargs...)
	ret0, _ := ret[0].(backup.Writer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDirWriter indicates an expected call of CreateDirWriter.
func (mr *MockOperationsMockRecorder) CreateDirWriter(ctx, storage, path any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, storage, path}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDirWriter", reflect.TypeOf((*MockOperations)(nil).CreateDirWriter), varargs...)
}

// DeleteFolder mocks base method.
func (m *MockOperations) DeleteFolder(ctx context.Context, storage model.Storage, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFolder", ctx, storage, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFolder indicates an expected call of DeleteFolder.
func (mr *MockOperationsMockRecorder) DeleteFolder(ctx, storage, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFolder", reflect.TypeOf((*MockOperations)(nil).DeleteFolder), ctx, storage, path)
}

// ReadFile mocks base method.
func (m *MockOperations) ReadFile(ctx context.Context, storage model.Storage, filepath string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFile", ctx, storage, filepath)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFile indicates an expected call of ReadFile.
func (mr *MockOperationsMockRecorder) ReadFile(ctx, storage, filepath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*MockOperations)(nil).ReadFile), ctx, storage, filepath)
}

// ReadFileNames mocks base method.
func (m *MockOperations) ReadFileNames(ctx context.Context, storage model.Storage, path, filterStr string, fromTime *time.Time) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFileNames", ctx, storage, path, filterStr, fromTime)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFileNames indicates an expected call of ReadFileNames.
func (mr *MockOperationsMockRecorder) ReadFileNames(ctx, storage, path, filterStr, fromTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFileNames", reflect.TypeOf((*MockOperations)(nil).ReadFileNames), ctx, storage, path, filterStr, fromTime)
}

// ReadFiles mocks base method.
func (m *MockOperations) ReadFiles(ctx context.Context, storage model.Storage, path, filterStr string) ([]*bytes.Buffer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFiles", ctx, storage, path, filterStr)
	ret0, _ := ret[0].([]*bytes.Buffer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFiles indicates an expected call of ReadFiles.
func (mr *MockOperationsMockRecorder) ReadFiles(ctx, storage, path, filterStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFiles", reflect.TypeOf((*MockOperations)(nil).ReadFiles), ctx, storage, path, filterStr)
}

// WriteDataFile mocks base method.
func (m *MockOperations) WriteDataFile(ctx context.Context, storage model.Storage, fileName string, content []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteDataFile", ctx, storage, fileName, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteDataFile indicates an expected call of WriteDataFile.
func (mr *MockOperationsMockRecorder) WriteDataFile(ctx, storage, fileName, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteDataFile", reflect.TypeOf((*MockOperations)(nil).WriteDataFile), ctx, storage, fileName, content)
}

// WriteMetadataFile mocks base method.
func (m *MockOperations) WriteMetadataFile(ctx context.Context, storage model.Storage, fileName string, content []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteMetadataFile", ctx, storage, fileName, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteMetadataFile indicates an expected call of WriteMetadataFile.
func (mr *MockOperationsMockRecorder) WriteMetadataFile(ctx, storage, fileName, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteMetadataFile", reflect.TypeOf((*MockOperations)(nil).WriteMetadataFile), ctx, storage, fileName, content)
}
