// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aerospike/aerospike-backup-service/v3/internal/server/handlers (interfaces: RunningBackupsRegistry)
//
// Generated by this command:
//
//	mockgen -package handlers -destination internal/server/handlers/mockgen.go github.com/aerospike/aerospike-backup-service/v3/internal/server/handlers RunningBackupsRegistry
//

// Package handlers is a generated GoMock package.
package handlers

import (
	reflect "reflect"

	model "github.com/aerospike/aerospike-backup-service/v3/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// MockRunningBackupsRegistry is a mock of RunningBackupsRegistry interface.
type MockRunningBackupsRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockRunningBackupsRegistryMockRecorder
	isgomock struct{}
}

// MockRunningBackupsRegistryMockRecorder is the mock recorder for MockRunningBackupsRegistry.
type MockRunningBackupsRegistryMockRecorder struct {
	mock *MockRunningBackupsRegistry
}

// NewMockRunningBackupsRegistry creates a new mock instance.
func NewMockRunningBackupsRegistry(ctrl *gomock.Controller) *MockRunningBackupsRegistry {
	mock := &MockRunningBackupsRegistry{ctrl: ctrl}
	mock.recorder = &MockRunningBackupsRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRunningBackupsRegistry) EXPECT() *MockRunningBackupsRegistryMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockRunningBackupsRegistry) Cancel(routineName string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Cancel", routineName)
}

// Cancel indicates an expected call of Cancel.
func (mr *MockRunningBackupsRegistryMockRecorder) Cancel(routineName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockRunningBackupsRegistry)(nil).Cancel), routineName)
}

// GetRoutineState mocks base method.
func (m *MockRunningBackupsRegistry) GetRoutineState(routine *model.BackupRoutine) model.RoutineState {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoutineState", routine)
	ret0, _ := ret[0].(model.RoutineState)
	return ret0
}

// GetRoutineState indicates an expected call of GetRoutineState.
func (mr *MockRunningBackupsRegistryMockRecorder) GetRoutineState(routine any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoutineState", reflect.TypeOf((*MockRunningBackupsRegistry)(nil).GetRoutineState), routine)
}

// GetRunningState mocks base method.
func (m *MockRunningBackupsRegistry) GetRunningState() map[string]model.RoutineState {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRunningState")
	ret0, _ := ret[0].(map[string]model.RoutineState)
	return ret0
}

// GetRunningState indicates an expected call of GetRunningState.
func (mr *MockRunningBackupsRegistryMockRecorder) GetRunningState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRunningState", reflect.TypeOf((*MockRunningBackupsRegistry)(nil).GetRunningState))
}
