// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aerospike/aerospike-backup-service/v3/internal/server/handlers (interfaces: runningBackupsRegistry,configRetriever,manager,configApplier)
//
// Generated by this command:
//
//	mockgen -package handlers -destination internal/server/handlers/mockgen.go -mock_names=runningBackupsRegistry=mockRunningBackupsRegistry,configRetriever=mockConfigRetriever,manager=mockManager,configApplier=mockConfigApplier github.com/aerospike/aerospike-backup-service/v3/internal/server/handlers runningBackupsRegistry,configRetriever,manager,configApplier
//

// Package handlers is a generated GoMock package.
package handlers

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/aerospike/aerospike-backup-service/v3/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// mockRunningBackupsRegistry is a mock of runningBackupsRegistry interface.
type mockRunningBackupsRegistry struct {
	ctrl     *gomock.Controller
	recorder *mockRunningBackupsRegistryMockRecorder
	isgomock struct{}
}

// mockRunningBackupsRegistryMockRecorder is the mock recorder for mockRunningBackupsRegistry.
type mockRunningBackupsRegistryMockRecorder struct {
	mock *mockRunningBackupsRegistry
}

// NewmockRunningBackupsRegistry creates a new mock instance.
func NewmockRunningBackupsRegistry(ctrl *gomock.Controller) *mockRunningBackupsRegistry {
	mock := &mockRunningBackupsRegistry{ctrl: ctrl}
	mock.recorder = &mockRunningBackupsRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *mockRunningBackupsRegistry) EXPECT() *mockRunningBackupsRegistryMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *mockRunningBackupsRegistry) Cancel(routineName string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Cancel", routineName)
}

// Cancel indicates an expected call of Cancel.
func (mr *mockRunningBackupsRegistryMockRecorder) Cancel(routineName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*mockRunningBackupsRegistry)(nil).Cancel), routineName)
}

// GetRoutineState mocks base method.
func (m *mockRunningBackupsRegistry) GetRoutineState(routine *model.BackupRoutine) model.RoutineState {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoutineState", routine)
	ret0, _ := ret[0].(model.RoutineState)
	return ret0
}

// GetRoutineState indicates an expected call of GetRoutineState.
func (mr *mockRunningBackupsRegistryMockRecorder) GetRoutineState(routine any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoutineState", reflect.TypeOf((*mockRunningBackupsRegistry)(nil).GetRoutineState), routine)
}

// GetRunningState mocks base method.
func (m *mockRunningBackupsRegistry) GetRunningState() map[string]model.RoutineState {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRunningState")
	ret0, _ := ret[0].(map[string]model.RoutineState)
	return ret0
}

// GetRunningState indicates an expected call of GetRunningState.
func (mr *mockRunningBackupsRegistryMockRecorder) GetRunningState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRunningState", reflect.TypeOf((*mockRunningBackupsRegistry)(nil).GetRunningState))
}

// mockConfigRetriever is a mock of configRetriever interface.
type mockConfigRetriever struct {
	ctrl     *gomock.Controller
	recorder *mockConfigRetrieverMockRecorder
	isgomock struct{}
}

// mockConfigRetrieverMockRecorder is the mock recorder for mockConfigRetriever.
type mockConfigRetrieverMockRecorder struct {
	mock *mockConfigRetriever
}

// NewmockConfigRetriever creates a new mock instance.
func NewmockConfigRetriever(ctrl *gomock.Controller) *mockConfigRetriever {
	mock := &mockConfigRetriever{ctrl: ctrl}
	mock.recorder = &mockConfigRetrieverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *mockConfigRetriever) EXPECT() *mockConfigRetrieverMockRecorder {
	return m.recorder
}

// RetrieveConfiguration mocks base method.
func (m *mockConfigRetriever) RetrieveConfiguration(ctx context.Context, routine *model.BackupRoutine, t time.Time) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetrieveConfiguration", ctx, routine, t)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RetrieveConfiguration indicates an expected call of RetrieveConfiguration.
func (mr *mockConfigRetrieverMockRecorder) RetrieveConfiguration(ctx, routine, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetrieveConfiguration", reflect.TypeOf((*mockConfigRetriever)(nil).RetrieveConfiguration), ctx, routine, t)
}

// mockManager is a mock of manager interface.
type mockManager struct {
	ctrl     *gomock.Controller
	recorder *mockManagerMockRecorder
	isgomock struct{}
}

// mockManagerMockRecorder is the mock recorder for mockManager.
type mockManagerMockRecorder struct {
	mock *mockManager
}

// NewmockManager creates a new mock instance.
func NewmockManager(ctrl *gomock.Controller) *mockManager {
	mock := &mockManager{ctrl: ctrl}
	mock.recorder = &mockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *mockManager) EXPECT() *mockManagerMockRecorder {
	return m.recorder
}

// Read mocks base method.
func (m *mockManager) Read(ctx context.Context) (*model.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", ctx)
	ret0, _ := ret[0].(*model.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *mockManagerMockRecorder) Read(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*mockManager)(nil).Read), ctx)
}

// Write mocks base method.
func (m *mockManager) Write(ctx context.Context, config *model.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", ctx, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *mockManagerMockRecorder) Write(ctx, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*mockManager)(nil).Write), ctx, config)
}

// mockConfigApplier is a mock of configApplier interface.
type mockConfigApplier struct {
	ctrl     *gomock.Controller
	recorder *mockConfigApplierMockRecorder
	isgomock struct{}
}

// mockConfigApplierMockRecorder is the mock recorder for mockConfigApplier.
type mockConfigApplierMockRecorder struct {
	mock *mockConfigApplier
}

// NewmockConfigApplier creates a new mock instance.
func NewmockConfigApplier(ctrl *gomock.Controller) *mockConfigApplier {
	mock := &mockConfigApplier{ctrl: ctrl}
	mock.recorder = &mockConfigApplierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *mockConfigApplier) EXPECT() *mockConfigApplierMockRecorder {
	return m.recorder
}

// ApplyNewConfig mocks base method.
func (m *mockConfigApplier) ApplyNewConfig(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyNewConfig", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyNewConfig indicates an expected call of ApplyNewConfig.
func (mr *mockConfigApplierMockRecorder) ApplyNewConfig(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyNewConfig", reflect.TypeOf((*mockConfigApplier)(nil).ApplyNewConfig), ctx)
}
