---
aerospike-clusters:
  cluster1:
    name: "cluster1"
    address: "localhost"
    port: 3000
    user: "tester"
    password: "psw"

storage:
  local1:
    name: "local1"
    type: 0
    path: "./testout"

backup-policies:
  policy-daily:
    name: "policy-daily"
    interval: 30000
    incr-interval: 5000
    type: 1
    source-cluster: "cluster1"
    storage: "local1"
    namespace: "test"
    set-list:
      - set1
    parallel: 1
    remove-files: false
    