aerospike-cluster:
  - name: absDefaultCluster
    host: "localhost"
    port: 3000
    user: "tester"
    password: "psw"

backup-storage:
  - name: absDefaultStorage
    type: 0
    path: ./testout

backup-policy:
  - name: absDefaultPolicy
    interval: 10000
    incr_interval: 3000
    type: 0
    source_cluster: absDefaultCluster
    storage: absDefaultStorage
    namespace: source-ns1
    parallel: 1
    set_list:
      - absDefaultSet
    remove_files: false