---
aerospike-cluster:
  cluster1:
      name: "cluster1"
      host: "localhost"
      port: 3000
      user: "tester"
      password: "psw"

backup-storage:
  - name: "local1"
    type: 0
    path: "./testout"

backup-policy:
  - name: "policy-daily"
    interval: 30000
    incr_interval: 5000
    type: 1
    source_cluster: "cluster1"
    storage: "local1"
    namespace: "test"
    set_list:
      - set1
    parallel: 1
    remove_files: false
    