---
aerospike-cluster:
  - name: "cluster1"
    host: "localhost"
    port: 3000

backup-storage:
  - name: "s3"
    type: 1
    s3_endpoint_override: "http://localhost:9000"
    s3_region: "eu-central-1"
    path: "s3://as-backup-bucket/test-backup"

backup-policy:
  - name: "policy-daily"
    interval: 10000
    type: 1
    source_cluster: "cluster1"
    storage: "s3"
    namespace: "test"
    parallel: 1
    