// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aerospike/aerospike-backup-service/v3/pkg/service/secret (interfaces: PasswordResolver,Resolver)
//
// Generated by this command:
//
//	mockgen -package secrets -destination pkg/service/secret/mockgen.go github.com/aerospike/aerospike-backup-service/v3/pkg/service/secret PasswordResolver,Resolver
//

// Package secrets is a generated GoMock package.
package secrets

import (
	context "context"
	reflect "reflect"

	model "github.com/aerospike/aerospike-backup-service/v3/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// MockPasswordResolver is a mock of PasswordResolver interface.
type MockPasswordResolver struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordResolverMockRecorder
	isgomock struct{}
}

// MockPasswordResolverMockRecorder is the mock recorder for MockPasswordResolver.
type MockPasswordResolverMockRecorder struct {
	mock *MockPasswordResolver
}

// NewMockPasswordResolver creates a new mock instance.
func NewMockPasswordResolver(ctrl *gomock.Controller) *MockPasswordResolver {
	mock := &MockPasswordResolver{ctrl: ctrl}
	mock.recorder = &MockPasswordResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordResolver) EXPECT() *MockPasswordResolverMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockPasswordResolver) Resolve(ctx context.Context, creds *model.Credentials) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx, creds)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockPasswordResolverMockRecorder) Resolve(ctx, creds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockPasswordResolver)(nil).Resolve), ctx, creds)
}

// MockResolver is a mock of Resolver interface.
type MockResolver struct {
	ctrl     *gomock.Controller
	recorder *MockResolverMockRecorder
	isgomock struct{}
}

// MockResolverMockRecorder is the mock recorder for MockResolver.
type MockResolverMockRecorder struct {
	mock *MockResolver
}

// NewMockResolver creates a new mock instance.
func NewMockResolver(ctrl *gomock.Controller) *MockResolver {
	mock := &MockResolver{ctrl: ctrl}
	mock.recorder = &MockResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResolver) EXPECT() *MockResolverMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockResolver) Resolve(ctx context.Context, agent *model.SecretAgent, value string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx, agent, value)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockResolverMockRecorder) Resolve(ctx, agent, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockResolver)(nil).Resolve), ctx, agent, value)
}
