// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aerospike/aerospike-backup-service/v3/pkg/service (interfaces: RestoreManager,BackupReaderWriter,BackupReader,RunningBackupsRegistry,RetentionManager,ClusterConfigWriter,CancelableBackupHandler,PathService,routineProvider,HistoryManager,BackupCompletionHandler,RestoreValidator)
//
// Generated by this command:
//
//	mockgen -package service -destination pkg/service/mockgen.go github.com/aerospike/aerospike-backup-service/v3/pkg/service RestoreManager,BackupReaderWriter,BackupReader,RunningBackupsRegistry,RetentionManager,ClusterConfigWriter,CancelableBackupHandler,PathService,routineProvider,HistoryManager,BackupCompletionHandler,RestoreValidator
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	slog "log/slog"
	reflect "reflect"
	time "time"

	model "github.com/aerospike/aerospike-backup-service/v3/pkg/model"
	backup "github.com/aerospike/backup-go"
	models "github.com/aerospike/backup-go/models"
	gomock "go.uber.org/mock/gomock"
)

// MockRestoreManager is a mock of RestoreManager interface.
type MockRestoreManager struct {
	ctrl     *gomock.Controller
	recorder *MockRestoreManagerMockRecorder
	isgomock struct{}
}

// MockRestoreManagerMockRecorder is the mock recorder for MockRestoreManager.
type MockRestoreManagerMockRecorder struct {
	mock *MockRestoreManager
}

// NewMockRestoreManager creates a new mock instance.
func NewMockRestoreManager(ctrl *gomock.Controller) *MockRestoreManager {
	mock := &MockRestoreManager{ctrl: ctrl}
	mock.recorder = &MockRestoreManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRestoreManager) EXPECT() *MockRestoreManagerMockRecorder {
	return m.recorder
}

// CancelRestore mocks base method.
func (m *MockRestoreManager) CancelRestore(jobID model.RestoreJobID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelRestore", jobID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelRestore indicates an expected call of CancelRestore.
func (mr *MockRestoreManagerMockRecorder) CancelRestore(jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelRestore", reflect.TypeOf((*MockRestoreManager)(nil).CancelRestore), jobID)
}

// GetFilteredJobs mocks base method.
func (m *MockRestoreManager) GetFilteredJobs(timeBounds model.TimeBounds, statusFilter model.StatusFilter) map[model.RestoreJobID]*model.RestoreJobStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilteredJobs", timeBounds, statusFilter)
	ret0, _ := ret[0].(map[model.RestoreJobID]*model.RestoreJobStatus)
	return ret0
}

// GetFilteredJobs indicates an expected call of GetFilteredJobs.
func (mr *MockRestoreManagerMockRecorder) GetFilteredJobs(timeBounds, statusFilter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilteredJobs", reflect.TypeOf((*MockRestoreManager)(nil).GetFilteredJobs), timeBounds, statusFilter)
}

// JobStatus mocks base method.
func (m *MockRestoreManager) JobStatus(jobID model.RestoreJobID) (*model.RestoreJobStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JobStatus", jobID)
	ret0, _ := ret[0].(*model.RestoreJobStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// JobStatus indicates an expected call of JobStatus.
func (mr *MockRestoreManagerMockRecorder) JobStatus(jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JobStatus", reflect.TypeOf((*MockRestoreManager)(nil).JobStatus), jobID)
}

// Restore mocks base method.
func (m *MockRestoreManager) Restore(ctx context.Context, request *model.RestoreRequest) (model.RestoreJobID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restore", ctx, request)
	ret0, _ := ret[0].(model.RestoreJobID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Restore indicates an expected call of Restore.
func (mr *MockRestoreManagerMockRecorder) Restore(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restore", reflect.TypeOf((*MockRestoreManager)(nil).Restore), ctx, request)
}

// RestoreByTime mocks base method.
func (m *MockRestoreManager) RestoreByTime(ctx context.Context, request *model.RestoreTimestampRequest) (model.RestoreJobID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreByTime", ctx, request)
	ret0, _ := ret[0].(model.RestoreJobID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RestoreByTime indicates an expected call of RestoreByTime.
func (mr *MockRestoreManagerMockRecorder) RestoreByTime(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreByTime", reflect.TypeOf((*MockRestoreManager)(nil).RestoreByTime), ctx, request)
}

// MockBackupReaderWriter is a mock of BackupReaderWriter interface.
type MockBackupReaderWriter struct {
	ctrl     *gomock.Controller
	recorder *MockBackupReaderWriterMockRecorder
	isgomock struct{}
}

// MockBackupReaderWriterMockRecorder is the mock recorder for MockBackupReaderWriter.
type MockBackupReaderWriterMockRecorder struct {
	mock *MockBackupReaderWriter
}

// NewMockBackupReaderWriter creates a new mock instance.
func NewMockBackupReaderWriter(ctrl *gomock.Controller) *MockBackupReaderWriter {
	mock := &MockBackupReaderWriter{ctrl: ctrl}
	mock.recorder = &MockBackupReaderWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackupReaderWriter) EXPECT() *MockBackupReaderWriterMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockBackupReaderWriter) Delete(ctx context.Context, routine *model.BackupRoutine, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, routine, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBackupReaderWriterMockRecorder) Delete(ctx, routine, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBackupReaderWriter)(nil).Delete), ctx, routine, path)
}

// GetBackups mocks base method.
func (m *MockBackupReaderWriter) GetBackups(ctx context.Context, filter BackupFilter) ([]model.BackupDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBackups", ctx, filter)
	ret0, _ := ret[0].([]model.BackupDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBackups indicates an expected call of GetBackups.
func (mr *MockBackupReaderWriterMockRecorder) GetBackups(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBackups", reflect.TypeOf((*MockBackupReaderWriter)(nil).GetBackups), ctx, filter)
}

// WriteBackupMetadata mocks base method.
func (m *MockBackupReaderWriter) WriteBackupMetadata(arg0 context.Context, arg1 *model.BackupRoutine, arg2 string, arg3 model.BackupMetadata) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteBackupMetadata", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteBackupMetadata indicates an expected call of WriteBackupMetadata.
func (mr *MockBackupReaderWriterMockRecorder) WriteBackupMetadata(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteBackupMetadata", reflect.TypeOf((*MockBackupReaderWriter)(nil).WriteBackupMetadata), arg0, arg1, arg2, arg3)
}

// MockBackupReader is a mock of BackupReader interface.
type MockBackupReader struct {
	ctrl     *gomock.Controller
	recorder *MockBackupReaderMockRecorder
	isgomock struct{}
}

// MockBackupReaderMockRecorder is the mock recorder for MockBackupReader.
type MockBackupReaderMockRecorder struct {
	mock *MockBackupReader
}

// NewMockBackupReader creates a new mock instance.
func NewMockBackupReader(ctrl *gomock.Controller) *MockBackupReader {
	mock := &MockBackupReader{ctrl: ctrl}
	mock.recorder = &MockBackupReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackupReader) EXPECT() *MockBackupReaderMockRecorder {
	return m.recorder
}

// GetBackups mocks base method.
func (m *MockBackupReader) GetBackups(ctx context.Context, filter BackupFilter) ([]model.BackupDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBackups", ctx, filter)
	ret0, _ := ret[0].([]model.BackupDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBackups indicates an expected call of GetBackups.
func (mr *MockBackupReaderMockRecorder) GetBackups(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBackups", reflect.TypeOf((*MockBackupReader)(nil).GetBackups), ctx, filter)
}

// MockRunningBackupsRegistry is a mock of RunningBackupsRegistry interface.
type MockRunningBackupsRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockRunningBackupsRegistryMockRecorder
	isgomock struct{}
}

// MockRunningBackupsRegistryMockRecorder is the mock recorder for MockRunningBackupsRegistry.
type MockRunningBackupsRegistryMockRecorder struct {
	mock *MockRunningBackupsRegistry
}

// NewMockRunningBackupsRegistry creates a new mock instance.
func NewMockRunningBackupsRegistry(ctrl *gomock.Controller) *MockRunningBackupsRegistry {
	mock := &MockRunningBackupsRegistry{ctrl: ctrl}
	mock.recorder = &MockRunningBackupsRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRunningBackupsRegistry) EXPECT() *MockRunningBackupsRegistryMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockRunningBackupsRegistry) Cancel(routineName string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Cancel", routineName)
}

// Cancel indicates an expected call of Cancel.
func (mr *MockRunningBackupsRegistryMockRecorder) Cancel(routineName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockRunningBackupsRegistry)(nil).Cancel), routineName)
}

// GetRoutineState mocks base method.
func (m *MockRunningBackupsRegistry) GetRoutineState(routine *model.BackupRoutine) *model.RoutineState {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoutineState", routine)
	ret0, _ := ret[0].(*model.RoutineState)
	return ret0
}

// GetRoutineState indicates an expected call of GetRoutineState.
func (mr *MockRunningBackupsRegistryMockRecorder) GetRoutineState(routine any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoutineState", reflect.TypeOf((*MockRunningBackupsRegistry)(nil).GetRoutineState), routine)
}

// GetRunningState mocks base method.
func (m *MockRunningBackupsRegistry) GetRunningState() map[string]*model.RoutineState {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRunningState")
	ret0, _ := ret[0].(map[string]*model.RoutineState)
	return ret0
}

// GetRunningState indicates an expected call of GetRunningState.
func (mr *MockRunningBackupsRegistryMockRecorder) GetRunningState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRunningState", reflect.TypeOf((*MockRunningBackupsRegistry)(nil).GetRunningState))
}

// SynchroniseBackupHistory mocks base method.
func (m *MockRunningBackupsRegistry) SynchroniseBackupHistory(ctx context.Context, routines []*model.BackupRoutine) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SynchroniseBackupHistory", ctx, routines)
}

// SynchroniseBackupHistory indicates an expected call of SynchroniseBackupHistory.
func (mr *MockRunningBackupsRegistryMockRecorder) SynchroniseBackupHistory(ctx, routines any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SynchroniseBackupHistory", reflect.TypeOf((*MockRunningBackupsRegistry)(nil).SynchroniseBackupHistory), ctx, routines)
}

// clearFailedBackup mocks base method.
func (m *MockRunningBackupsRegistry) clearFailedBackup(routineName string, jt jobType) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "clearFailedBackup", routineName, jt)
}

// clearFailedBackup indicates an expected call of clearFailedBackup.
func (mr *MockRunningBackupsRegistryMockRecorder) clearFailedBackup(routineName, jt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "clearFailedBackup", reflect.TypeOf((*MockRunningBackupsRegistry)(nil).clearFailedBackup), routineName, jt)
}

// recordSuccessfulBackup mocks base method.
func (m *MockRunningBackupsRegistry) recordSuccessfulBackup(routineName string, jt jobType, timestamp time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "recordSuccessfulBackup", routineName, jt, timestamp)
}

// recordSuccessfulBackup indicates an expected call of recordSuccessfulBackup.
func (mr *MockRunningBackupsRegistryMockRecorder) recordSuccessfulBackup(routineName, jt, timestamp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "recordSuccessfulBackup", reflect.TypeOf((*MockRunningBackupsRegistry)(nil).recordSuccessfulBackup), routineName, jt, timestamp)
}

// register mocks base method.
func (m *MockRunningBackupsRegistry) register(routineName string, jt jobType, handler CancelableBackupHandler) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "register", routineName, jt, handler)
}

// register indicates an expected call of register.
func (mr *MockRunningBackupsRegistryMockRecorder) register(routineName, jt, handler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "register", reflect.TypeOf((*MockRunningBackupsRegistry)(nil).register), routineName, jt, handler)
}

// MockRetentionManager is a mock of RetentionManager interface.
type MockRetentionManager struct {
	ctrl     *gomock.Controller
	recorder *MockRetentionManagerMockRecorder
	isgomock struct{}
}

// MockRetentionManagerMockRecorder is the mock recorder for MockRetentionManager.
type MockRetentionManagerMockRecorder struct {
	mock *MockRetentionManager
}

// NewMockRetentionManager creates a new mock instance.
func NewMockRetentionManager(ctrl *gomock.Controller) *MockRetentionManager {
	mock := &MockRetentionManager{ctrl: ctrl}
	mock.recorder = &MockRetentionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRetentionManager) EXPECT() *MockRetentionManagerMockRecorder {
	return m.recorder
}

// deleteOldBackups mocks base method.
func (m *MockRetentionManager) deleteOldBackups(ctx context.Context, routine *model.BackupRoutine) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "deleteOldBackups", ctx, routine)
	ret0, _ := ret[0].(error)
	return ret0
}

// deleteOldBackups indicates an expected call of deleteOldBackups.
func (mr *MockRetentionManagerMockRecorder) deleteOldBackups(ctx, routine any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "deleteOldBackups", reflect.TypeOf((*MockRetentionManager)(nil).deleteOldBackups), ctx, routine)
}

// MockClusterConfigWriter is a mock of ClusterConfigWriter interface.
type MockClusterConfigWriter struct {
	ctrl     *gomock.Controller
	recorder *MockClusterConfigWriterMockRecorder
	isgomock struct{}
}

// MockClusterConfigWriterMockRecorder is the mock recorder for MockClusterConfigWriter.
type MockClusterConfigWriterMockRecorder struct {
	mock *MockClusterConfigWriter
}

// NewMockClusterConfigWriter creates a new mock instance.
func NewMockClusterConfigWriter(ctrl *gomock.Controller) *MockClusterConfigWriter {
	mock := &MockClusterConfigWriter{ctrl: ctrl}
	mock.recorder = &MockClusterConfigWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClusterConfigWriter) EXPECT() *MockClusterConfigWriterMockRecorder {
	return m.recorder
}

// Write mocks base method.
func (m *MockClusterConfigWriter) Write(ctx context.Context, routine *model.BackupRoutine, timestamp time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", ctx, routine, timestamp)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockClusterConfigWriterMockRecorder) Write(ctx, routine, timestamp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockClusterConfigWriter)(nil).Write), ctx, routine, timestamp)
}

// MockCancelableBackupHandler is a mock of CancelableBackupHandler interface.
type MockCancelableBackupHandler struct {
	ctrl     *gomock.Controller
	recorder *MockCancelableBackupHandlerMockRecorder
	isgomock struct{}
}

// MockCancelableBackupHandlerMockRecorder is the mock recorder for MockCancelableBackupHandler.
type MockCancelableBackupHandlerMockRecorder struct {
	mock *MockCancelableBackupHandler
}

// NewMockCancelableBackupHandler creates a new mock instance.
func NewMockCancelableBackupHandler(ctrl *gomock.Controller) *MockCancelableBackupHandler {
	mock := &MockCancelableBackupHandler{ctrl: ctrl}
	mock.recorder = &MockCancelableBackupHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCancelableBackupHandler) EXPECT() *MockCancelableBackupHandlerMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockCancelableBackupHandler) Cancel() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Cancel")
}

// Cancel indicates an expected call of Cancel.
func (mr *MockCancelableBackupHandlerMockRecorder) Cancel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockCancelableBackupHandler)(nil).Cancel))
}

// GetMetrics mocks base method.
func (m *MockCancelableBackupHandler) GetMetrics() *models.Metrics {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetrics")
	ret0, _ := ret[0].(*models.Metrics)
	return ret0
}

// GetMetrics indicates an expected call of GetMetrics.
func (mr *MockCancelableBackupHandlerMockRecorder) GetMetrics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetrics", reflect.TypeOf((*MockCancelableBackupHandler)(nil).GetMetrics))
}

// GetStats mocks base method.
func (m *MockCancelableBackupHandler) GetStats() *models.BackupStats {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats")
	ret0, _ := ret[0].(*models.BackupStats)
	return ret0
}

// GetStats indicates an expected call of GetStats.
func (mr *MockCancelableBackupHandlerMockRecorder) GetStats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockCancelableBackupHandler)(nil).GetStats))
}

// Wait mocks base method.
func (m *MockCancelableBackupHandler) Wait(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Wait", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Wait indicates an expected call of Wait.
func (mr *MockCancelableBackupHandlerMockRecorder) Wait(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wait", reflect.TypeOf((*MockCancelableBackupHandler)(nil).Wait), arg0)
}

// MockPathService is a mock of PathService interface.
type MockPathService struct {
	ctrl     *gomock.Controller
	recorder *MockPathServiceMockRecorder
	isgomock struct{}
}

// MockPathServiceMockRecorder is the mock recorder for MockPathService.
type MockPathServiceMockRecorder struct {
	mock *MockPathService
}

// NewMockPathService creates a new mock instance.
func NewMockPathService(ctrl *gomock.Controller) *MockPathService {
	mock := &MockPathService{ctrl: ctrl}
	mock.recorder = &MockPathServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPathService) EXPECT() *MockPathServiceMockRecorder {
	return m.recorder
}

// ExtractTimestampFromPath mocks base method.
func (m *MockPathService) ExtractTimestampFromPath(path string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractTimestampFromPath", path)
	ret0, _ := ret[0].(string)
	return ret0
}

// ExtractTimestampFromPath indicates an expected call of ExtractTimestampFromPath.
func (mr *MockPathServiceMockRecorder) ExtractTimestampFromPath(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractTimestampFromPath", reflect.TypeOf((*MockPathService)(nil).ExtractTimestampFromPath), path)
}

// GetBackupPath mocks base method.
func (m *MockPathService) GetBackupPath(routineName string, backupType jobType, namespace string, timestamp time.Time) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBackupPath", routineName, backupType, namespace, timestamp)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetBackupPath indicates an expected call of GetBackupPath.
func (mr *MockPathServiceMockRecorder) GetBackupPath(routineName, backupType, namespace, timestamp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBackupPath", reflect.TypeOf((*MockPathService)(nil).GetBackupPath), routineName, backupType, namespace, timestamp)
}

// GetConfigurationFilePath mocks base method.
func (m *MockPathService) GetConfigurationFilePath(routineName string, timestamp time.Time, index int) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigurationFilePath", routineName, timestamp, index)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetConfigurationFilePath indicates an expected call of GetConfigurationFilePath.
func (mr *MockPathServiceMockRecorder) GetConfigurationFilePath(routineName, timestamp, index any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigurationFilePath", reflect.TypeOf((*MockPathService)(nil).GetConfigurationFilePath), routineName, timestamp, index)
}

// GetConfigurationPath mocks base method.
func (m *MockPathService) GetConfigurationPath(routineName string, timestamp time.Time) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigurationPath", routineName, timestamp)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetConfigurationPath indicates an expected call of GetConfigurationPath.
func (mr *MockPathServiceMockRecorder) GetConfigurationPath(routineName, timestamp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigurationPath", reflect.TypeOf((*MockPathService)(nil).GetConfigurationPath), routineName, timestamp)
}

// GetTimestampPath mocks base method.
func (m *MockPathService) GetTimestampPath(routineName string, timestamp time.Time, backupType jobType) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTimestampPath", routineName, timestamp, backupType)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetTimestampPath indicates an expected call of GetTimestampPath.
func (mr *MockPathServiceMockRecorder) GetTimestampPath(routineName, timestamp, backupType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTimestampPath", reflect.TypeOf((*MockPathService)(nil).GetTimestampPath), routineName, timestamp, backupType)
}

// MockroutineProvider is a mock of routineProvider interface.
type MockroutineProvider struct {
	ctrl     *gomock.Controller
	recorder *MockroutineProviderMockRecorder
	isgomock struct{}
}

// MockroutineProviderMockRecorder is the mock recorder for MockroutineProvider.
type MockroutineProviderMockRecorder struct {
	mock *MockroutineProvider
}

// NewMockroutineProvider creates a new mock instance.
func NewMockroutineProvider(ctrl *gomock.Controller) *MockroutineProvider {
	mock := &MockroutineProvider{ctrl: ctrl}
	mock.recorder = &MockroutineProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockroutineProvider) EXPECT() *MockroutineProviderMockRecorder {
	return m.recorder
}

// Routines mocks base method.
func (m *MockroutineProvider) Routines() map[string]*model.BackupRoutine {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Routines")
	ret0, _ := ret[0].(map[string]*model.BackupRoutine)
	return ret0
}

// Routines indicates an expected call of Routines.
func (mr *MockroutineProviderMockRecorder) Routines() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Routines", reflect.TypeOf((*MockroutineProvider)(nil).Routines))
}

// MockHistoryManager is a mock of HistoryManager interface.
type MockHistoryManager struct {
	ctrl     *gomock.Controller
	recorder *MockHistoryManagerMockRecorder
	isgomock struct{}
}

// MockHistoryManagerMockRecorder is the mock recorder for MockHistoryManager.
type MockHistoryManagerMockRecorder struct {
	mock *MockHistoryManager
}

// NewMockHistoryManager creates a new mock instance.
func NewMockHistoryManager(ctrl *gomock.Controller) *MockHistoryManager {
	mock := &MockHistoryManager{ctrl: ctrl}
	mock.recorder = &MockHistoryManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHistoryManager) EXPECT() *MockHistoryManagerMockRecorder {
	return m.recorder
}

// FindLastRun mocks base method.
func (m *MockHistoryManager) FindLastRun(ctx context.Context, routine *model.BackupRoutine) (*model.BackupTime, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLastRun", ctx, routine)
	ret0, _ := ret[0].(*model.BackupTime)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLastRun indicates an expected call of FindLastRun.
func (mr *MockHistoryManagerMockRecorder) FindLastRun(ctx, routine any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLastRun", reflect.TypeOf((*MockHistoryManager)(nil).FindLastRun), ctx, routine)
}

// MockBackupCompletionHandler is a mock of BackupCompletionHandler interface.
type MockBackupCompletionHandler struct {
	ctrl     *gomock.Controller
	recorder *MockBackupCompletionHandlerMockRecorder
	isgomock struct{}
}

// MockBackupCompletionHandlerMockRecorder is the mock recorder for MockBackupCompletionHandler.
type MockBackupCompletionHandlerMockRecorder struct {
	mock *MockBackupCompletionHandler
}

// NewMockBackupCompletionHandler creates a new mock instance.
func NewMockBackupCompletionHandler(ctrl *gomock.Controller) *MockBackupCompletionHandler {
	mock := &MockBackupCompletionHandler{ctrl: ctrl}
	mock.recorder = &MockBackupCompletionHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackupCompletionHandler) EXPECT() *MockBackupCompletionHandlerMockRecorder {
	return m.recorder
}

// OnFailure mocks base method.
func (m *MockBackupCompletionHandler) OnFailure(routine *model.BackupRoutine, jobType jobType) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnFailure", routine, jobType)
}

// OnFailure indicates an expected call of OnFailure.
func (mr *MockBackupCompletionHandlerMockRecorder) OnFailure(routine, jobType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnFailure", reflect.TypeOf((*MockBackupCompletionHandler)(nil).OnFailure), routine, jobType)
}

// OnSuccess mocks base method.
func (m *MockBackupCompletionHandler) OnSuccess(ctx context.Context, routine *model.BackupRoutine, jobType jobType, timestamp time.Time, logger *slog.Logger) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnSuccess", ctx, routine, jobType, timestamp, logger)
}

// OnSuccess indicates an expected call of OnSuccess.
func (mr *MockBackupCompletionHandlerMockRecorder) OnSuccess(ctx, routine, jobType, timestamp, logger any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnSuccess", reflect.TypeOf((*MockBackupCompletionHandler)(nil).OnSuccess), ctx, routine, jobType, timestamp, logger)
}

// MockRestoreValidator is a mock of RestoreValidator interface.
type MockRestoreValidator struct {
	ctrl     *gomock.Controller
	recorder *MockRestoreValidatorMockRecorder
	isgomock struct{}
}

// MockRestoreValidatorMockRecorder is the mock recorder for MockRestoreValidator.
type MockRestoreValidatorMockRecorder struct {
	mock *MockRestoreValidator
}

// NewMockRestoreValidator creates a new mock instance.
func NewMockRestoreValidator(ctrl *gomock.Controller) *MockRestoreValidator {
	mock := &MockRestoreValidator{ctrl: ctrl}
	mock.recorder = &MockRestoreValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRestoreValidator) EXPECT() *MockRestoreValidatorMockRecorder {
	return m.recorder
}

// ValidatePath mocks base method.
func (m *MockRestoreValidator) ValidatePath(ctx context.Context, request *model.RestoreRequest, infoGetter backup.InfoGetter, backups []model.BackupDetails) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidatePath", ctx, request, infoGetter, backups)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidatePath indicates an expected call of ValidatePath.
func (mr *MockRestoreValidatorMockRecorder) ValidatePath(ctx, request, infoGetter, backups any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatePath", reflect.TypeOf((*MockRestoreValidator)(nil).ValidatePath), ctx, request, infoGetter, backups)
}

// ValidateTimestamp mocks base method.
func (m *MockRestoreValidator) ValidateTimestamp(ctx context.Context, request *model.RestoreTimestampRequest, infoGetter backup.InfoGetter, backupsByNamespace map[string][]model.BackupDetails) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateTimestamp", ctx, request, infoGetter, backupsByNamespace)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateTimestamp indicates an expected call of ValidateTimestamp.
func (mr *MockRestoreValidatorMockRecorder) ValidateTimestamp(ctx, request, infoGetter, backupsByNamespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateTimestamp", reflect.TypeOf((*MockRestoreValidator)(nil).ValidateTimestamp), ctx, request, infoGetter, backupsByNamespace)
}
