// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aerospike/aerospike-backup-service/v3/pkg/service (interfaces: RestoreManager,BackupReaderWriter,BackupReader)
//
// Generated by this command:
//
//	mockgen -package service -destination /Users/ak/work/aerospike-backup-service/pkg/service/mockgen.go github.com/aerospike/aerospike-backup-service/v3/pkg/service RestoreManager,BackupReaderWriter,BackupReader
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	model "github.com/aerospike/aerospike-backup-service/v3/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// MockRestoreManager is a mock of RestoreManager interface.
type MockRestoreManager struct {
	ctrl     *gomock.Controller
	recorder *MockRestoreManagerMockRecorder
	isgomock struct{}
}

// MockRestoreManagerMockRecorder is the mock recorder for MockRestoreManager.
type MockRestoreManagerMockRecorder struct {
	mock *MockRestoreManager
}

// NewMockRestoreManager creates a new mock instance.
func NewMockRestoreManager(ctrl *gomock.Controller) *MockRestoreManager {
	mock := &MockRestoreManager{ctrl: ctrl}
	mock.recorder = &MockRestoreManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRestoreManager) EXPECT() *MockRestoreManagerMockRecorder {
	return m.recorder
}

// CancelRestore mocks base method.
func (m *MockRestoreManager) CancelRestore(jobID model.RestoreJobID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelRestore", jobID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelRestore indicates an expected call of CancelRestore.
func (mr *MockRestoreManagerMockRecorder) CancelRestore(jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelRestore", reflect.TypeOf((*MockRestoreManager)(nil).CancelRestore), jobID)
}

// JobStatus mocks base method.
func (m *MockRestoreManager) JobStatus(jobID model.RestoreJobID) (*model.RestoreJobStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JobStatus", jobID)
	ret0, _ := ret[0].(*model.RestoreJobStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// JobStatus indicates an expected call of JobStatus.
func (mr *MockRestoreManagerMockRecorder) JobStatus(jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JobStatus", reflect.TypeOf((*MockRestoreManager)(nil).JobStatus), jobID)
}

// Restore mocks base method.
func (m *MockRestoreManager) Restore(request *model.RestoreRequest) (model.RestoreJobID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restore", request)
	ret0, _ := ret[0].(model.RestoreJobID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Restore indicates an expected call of Restore.
func (mr *MockRestoreManagerMockRecorder) Restore(request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restore", reflect.TypeOf((*MockRestoreManager)(nil).Restore), request)
}

// RestoreByTime mocks base method.
func (m *MockRestoreManager) RestoreByTime(ctx context.Context, request *model.RestoreTimestampRequest) (model.RestoreJobID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreByTime", ctx, request)
	ret0, _ := ret[0].(model.RestoreJobID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RestoreByTime indicates an expected call of RestoreByTime.
func (mr *MockRestoreManagerMockRecorder) RestoreByTime(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreByTime", reflect.TypeOf((*MockRestoreManager)(nil).RestoreByTime), ctx, request)
}

// MockBackupReaderWriter is a mock of BackupReaderWriter interface.
type MockBackupReaderWriter struct {
	ctrl     *gomock.Controller
	recorder *MockBackupReaderWriterMockRecorder
	isgomock struct{}
}

// MockBackupReaderWriterMockRecorder is the mock recorder for MockBackupReaderWriter.
type MockBackupReaderWriterMockRecorder struct {
	mock *MockBackupReaderWriter
}

// NewMockBackupReaderWriter creates a new mock instance.
func NewMockBackupReaderWriter(ctrl *gomock.Controller) *MockBackupReaderWriter {
	mock := &MockBackupReaderWriter{ctrl: ctrl}
	mock.recorder = &MockBackupReaderWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackupReaderWriter) EXPECT() *MockBackupReaderWriterMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockBackupReaderWriter) Delete(ctx context.Context, routineName, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, routineName, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBackupReaderWriterMockRecorder) Delete(ctx, routineName, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBackupReaderWriter)(nil).Delete), ctx, routineName, path)
}

// GetBackups mocks base method.
func (m *MockBackupReaderWriter) GetBackups(ctx context.Context, filter BackupFilter) ([]model.BackupDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBackups", ctx, filter)
	ret0, _ := ret[0].([]model.BackupDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBackups indicates an expected call of GetBackups.
func (mr *MockBackupReaderWriterMockRecorder) GetBackups(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBackups", reflect.TypeOf((*MockBackupReaderWriter)(nil).GetBackups), ctx, filter)
}

// WriteBackupMetadata mocks base method.
func (m *MockBackupReaderWriter) WriteBackupMetadata(ctx context.Context, routineName, path string, metadata model.BackupMetadata) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteBackupMetadata", ctx, routineName, path, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteBackupMetadata indicates an expected call of WriteBackupMetadata.
func (mr *MockBackupReaderWriterMockRecorder) WriteBackupMetadata(ctx, routineName, path, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteBackupMetadata", reflect.TypeOf((*MockBackupReaderWriter)(nil).WriteBackupMetadata), ctx, routineName, path, metadata)
}

// MockBackupReader is a mock of BackupReader interface.
type MockBackupReader struct {
	ctrl     *gomock.Controller
	recorder *MockBackupReaderMockRecorder
	isgomock struct{}
}

// MockBackupReaderMockRecorder is the mock recorder for MockBackupReader.
type MockBackupReaderMockRecorder struct {
	mock *MockBackupReader
}

// NewMockBackupReader creates a new mock instance.
func NewMockBackupReader(ctrl *gomock.Controller) *MockBackupReader {
	mock := &MockBackupReader{ctrl: ctrl}
	mock.recorder = &MockBackupReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackupReader) EXPECT() *MockBackupReaderMockRecorder {
	return m.recorder
}

// GetBackups mocks base method.
func (m *MockBackupReader) GetBackups(ctx context.Context, filter BackupFilter) ([]model.BackupDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBackups", ctx, filter)
	ret0, _ := ret[0].([]model.BackupDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBackups indicates an expected call of GetBackups.
func (mr *MockBackupReaderMockRecorder) GetBackups(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBackups", reflect.TypeOf((*MockBackupReader)(nil).GetBackups), ctx, filter)
}
