// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aerospike/aerospike-backup-service/v3/pkg/service (interfaces: RestoreManager,BackupReaderWriter,BackupReader,RunningBackupsRegistry,RetentionManager,ClusterConfigWriter,CancelableBackupHandler)
//
// Generated by this command:
//
//	mockgen -package service -destination /Users/ak/work/aerospike-backup-service/pkg/service/mockgen.go github.com/aerospike/aerospike-backup-service/v3/pkg/service RestoreManager,BackupReaderWriter,BackupReader,RunningBackupsRegistry,RetentionManager,ClusterConfigWriter,CancelableBackupHandler
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/aerospike/aerospike-backup-service/v3/pkg/model"
	models "github.com/aerospike/backup-go/models"
	gomock "go.uber.org/mock/gomock"
)

// MockRestoreManager is a mock of RestoreManager interface.
type MockRestoreManager struct {
	ctrl     *gomock.Controller
	recorder *MockRestoreManagerMockRecorder
	isgomock struct{}
}

// MockRestoreManagerMockRecorder is the mock recorder for MockRestoreManager.
type MockRestoreManagerMockRecorder struct {
	mock *MockRestoreManager
}

// NewMockRestoreManager creates a new mock instance.
func NewMockRestoreManager(ctrl *gomock.Controller) *MockRestoreManager {
	mock := &MockRestoreManager{ctrl: ctrl}
	mock.recorder = &MockRestoreManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRestoreManager) EXPECT() *MockRestoreManagerMockRecorder {
	return m.recorder
}

// CancelRestore mocks base method.
func (m *MockRestoreManager) CancelRestore(jobID model.RestoreJobID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelRestore", jobID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelRestore indicates an expected call of CancelRestore.
func (mr *MockRestoreManagerMockRecorder) CancelRestore(jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelRestore", reflect.TypeOf((*MockRestoreManager)(nil).CancelRestore), jobID)
}

// GetFilteredJobs mocks base method.
func (m *MockRestoreManager) GetFilteredJobs(timeBounds model.TimeBounds, statusFilter model.StatusFilter) map[model.RestoreJobID]*model.RestoreJobStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilteredJobs", timeBounds, statusFilter)
	ret0, _ := ret[0].(map[model.RestoreJobID]*model.RestoreJobStatus)
	return ret0
}

// GetFilteredJobs indicates an expected call of GetFilteredJobs.
func (mr *MockRestoreManagerMockRecorder) GetFilteredJobs(timeBounds, statusFilter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilteredJobs", reflect.TypeOf((*MockRestoreManager)(nil).GetFilteredJobs), timeBounds, statusFilter)
}

// JobStatus mocks base method.
func (m *MockRestoreManager) JobStatus(jobID model.RestoreJobID) (*model.RestoreJobStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JobStatus", jobID)
	ret0, _ := ret[0].(*model.RestoreJobStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// JobStatus indicates an expected call of JobStatus.
func (mr *MockRestoreManagerMockRecorder) JobStatus(jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JobStatus", reflect.TypeOf((*MockRestoreManager)(nil).JobStatus), jobID)
}

// Restore mocks base method.
func (m *MockRestoreManager) Restore(request *model.RestoreRequest) (model.RestoreJobID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restore", request)
	ret0, _ := ret[0].(model.RestoreJobID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Restore indicates an expected call of Restore.
func (mr *MockRestoreManagerMockRecorder) Restore(request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restore", reflect.TypeOf((*MockRestoreManager)(nil).Restore), request)
}

// RestoreByTime mocks base method.
func (m *MockRestoreManager) RestoreByTime(ctx context.Context, request *model.RestoreTimestampRequest) (model.RestoreJobID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreByTime", ctx, request)
	ret0, _ := ret[0].(model.RestoreJobID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RestoreByTime indicates an expected call of RestoreByTime.
func (mr *MockRestoreManagerMockRecorder) RestoreByTime(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreByTime", reflect.TypeOf((*MockRestoreManager)(nil).RestoreByTime), ctx, request)
}

// MockBackupReaderWriter is a mock of BackupReaderWriter interface.
type MockBackupReaderWriter struct {
	ctrl     *gomock.Controller
	recorder *MockBackupReaderWriterMockRecorder
	isgomock struct{}
}

// MockBackupReaderWriterMockRecorder is the mock recorder for MockBackupReaderWriter.
type MockBackupReaderWriterMockRecorder struct {
	mock *MockBackupReaderWriter
}

// NewMockBackupReaderWriter creates a new mock instance.
func NewMockBackupReaderWriter(ctrl *gomock.Controller) *MockBackupReaderWriter {
	mock := &MockBackupReaderWriter{ctrl: ctrl}
	mock.recorder = &MockBackupReaderWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackupReaderWriter) EXPECT() *MockBackupReaderWriterMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockBackupReaderWriter) Delete(ctx context.Context, routineName, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, routineName, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBackupReaderWriterMockRecorder) Delete(ctx, routineName, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBackupReaderWriter)(nil).Delete), ctx, routineName, path)
}

// GetBackups mocks base method.
func (m *MockBackupReaderWriter) GetBackups(ctx context.Context, filter BackupFilter) ([]model.BackupDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBackups", ctx, filter)
	ret0, _ := ret[0].([]model.BackupDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBackups indicates an expected call of GetBackups.
func (mr *MockBackupReaderWriterMockRecorder) GetBackups(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBackups", reflect.TypeOf((*MockBackupReaderWriter)(nil).GetBackups), ctx, filter)
}

// WriteBackupMetadata mocks base method.
func (m *MockBackupReaderWriter) WriteBackupMetadata(ctx context.Context, routineName, path string, metadata model.BackupMetadata) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteBackupMetadata", ctx, routineName, path, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteBackupMetadata indicates an expected call of WriteBackupMetadata.
func (mr *MockBackupReaderWriterMockRecorder) WriteBackupMetadata(ctx, routineName, path, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteBackupMetadata", reflect.TypeOf((*MockBackupReaderWriter)(nil).WriteBackupMetadata), ctx, routineName, path, metadata)
}

// MockBackupReader is a mock of BackupReader interface.
type MockBackupReader struct {
	ctrl     *gomock.Controller
	recorder *MockBackupReaderMockRecorder
	isgomock struct{}
}

// MockBackupReaderMockRecorder is the mock recorder for MockBackupReader.
type MockBackupReaderMockRecorder struct {
	mock *MockBackupReader
}

// NewMockBackupReader creates a new mock instance.
func NewMockBackupReader(ctrl *gomock.Controller) *MockBackupReader {
	mock := &MockBackupReader{ctrl: ctrl}
	mock.recorder = &MockBackupReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackupReader) EXPECT() *MockBackupReaderMockRecorder {
	return m.recorder
}

// GetBackups mocks base method.
func (m *MockBackupReader) GetBackups(ctx context.Context, filter BackupFilter) ([]model.BackupDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBackups", ctx, filter)
	ret0, _ := ret[0].([]model.BackupDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBackups indicates an expected call of GetBackups.
func (mr *MockBackupReaderMockRecorder) GetBackups(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBackups", reflect.TypeOf((*MockBackupReader)(nil).GetBackups), ctx, filter)
}

// MockRunningBackupsRegistry is a mock of RunningBackupsRegistry interface.
type MockRunningBackupsRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockRunningBackupsRegistryMockRecorder
	isgomock struct{}
}

// MockRunningBackupsRegistryMockRecorder is the mock recorder for MockRunningBackupsRegistry.
type MockRunningBackupsRegistryMockRecorder struct {
	mock *MockRunningBackupsRegistry
}

// NewMockRunningBackupsRegistry creates a new mock instance.
func NewMockRunningBackupsRegistry(ctrl *gomock.Controller) *MockRunningBackupsRegistry {
	mock := &MockRunningBackupsRegistry{ctrl: ctrl}
	mock.recorder = &MockRunningBackupsRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRunningBackupsRegistry) EXPECT() *MockRunningBackupsRegistryMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockRunningBackupsRegistry) Cancel(routineName string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Cancel", routineName)
}

// Cancel indicates an expected call of Cancel.
func (mr *MockRunningBackupsRegistryMockRecorder) Cancel(routineName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockRunningBackupsRegistry)(nil).Cancel), routineName)
}

// GetRoutineState mocks base method.
func (m *MockRunningBackupsRegistry) GetRoutineState(routineName string) *model.RoutineState {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoutineState", routineName)
	ret0, _ := ret[0].(*model.RoutineState)
	return ret0
}

// GetRoutineState indicates an expected call of GetRoutineState.
func (mr *MockRunningBackupsRegistryMockRecorder) GetRoutineState(routineName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoutineState", reflect.TypeOf((*MockRunningBackupsRegistry)(nil).GetRoutineState), routineName)
}

// GetRunningState mocks base method.
func (m *MockRunningBackupsRegistry) GetRunningState() map[string]*model.RoutineState {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRunningState")
	ret0, _ := ret[0].(map[string]*model.RoutineState)
	return ret0
}

// GetRunningState indicates an expected call of GetRunningState.
func (mr *MockRunningBackupsRegistryMockRecorder) GetRunningState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRunningState", reflect.TypeOf((*MockRunningBackupsRegistry)(nil).GetRunningState))
}

// SynchroniseBackupHistory mocks base method.
func (m *MockRunningBackupsRegistry) SynchroniseBackupHistory() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SynchroniseBackupHistory")
}

// SynchroniseBackupHistory indicates an expected call of SynchroniseBackupHistory.
func (mr *MockRunningBackupsRegistryMockRecorder) SynchroniseBackupHistory() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SynchroniseBackupHistory", reflect.TypeOf((*MockRunningBackupsRegistry)(nil).SynchroniseBackupHistory))
}

// register mocks base method.
func (m *MockRunningBackupsRegistry) register(routineName string, jt jobType, handler CancelableBackupHandler) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "register", routineName, jt, handler)
}

// register indicates an expected call of register.
func (mr *MockRunningBackupsRegistryMockRecorder) register(routineName, jt, handler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "register", reflect.TypeOf((*MockRunningBackupsRegistry)(nil).register), routineName, jt, handler)
}

// remove mocks base method.
func (m *MockRunningBackupsRegistry) remove(routineName string, jt jobType) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "remove", routineName, jt)
}

// remove indicates an expected call of remove.
func (mr *MockRunningBackupsRegistryMockRecorder) remove(routineName, jt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "remove", reflect.TypeOf((*MockRunningBackupsRegistry)(nil).remove), routineName, jt)
}

// unregister mocks base method.
func (m *MockRunningBackupsRegistry) unregister(routineName string, jt jobType, timestamp time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "unregister", routineName, jt, timestamp)
}

// unregister indicates an expected call of unregister.
func (mr *MockRunningBackupsRegistryMockRecorder) unregister(routineName, jt, timestamp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "unregister", reflect.TypeOf((*MockRunningBackupsRegistry)(nil).unregister), routineName, jt, timestamp)
}

// MockRetentionManager is a mock of RetentionManager interface.
type MockRetentionManager struct {
	ctrl     *gomock.Controller
	recorder *MockRetentionManagerMockRecorder
	isgomock struct{}
}

// MockRetentionManagerMockRecorder is the mock recorder for MockRetentionManager.
type MockRetentionManagerMockRecorder struct {
	mock *MockRetentionManager
}

// NewMockRetentionManager creates a new mock instance.
func NewMockRetentionManager(ctrl *gomock.Controller) *MockRetentionManager {
	mock := &MockRetentionManager{ctrl: ctrl}
	mock.recorder = &MockRetentionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRetentionManager) EXPECT() *MockRetentionManagerMockRecorder {
	return m.recorder
}

// deleteOldBackups mocks base method.
func (m *MockRetentionManager) deleteOldBackups(ctx context.Context, routineName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "deleteOldBackups", ctx, routineName)
	ret0, _ := ret[0].(error)
	return ret0
}

// deleteOldBackups indicates an expected call of deleteOldBackups.
func (mr *MockRetentionManagerMockRecorder) deleteOldBackups(ctx, routineName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "deleteOldBackups", reflect.TypeOf((*MockRetentionManager)(nil).deleteOldBackups), ctx, routineName)
}

// MockClusterConfigWriter is a mock of ClusterConfigWriter interface.
type MockClusterConfigWriter struct {
	ctrl     *gomock.Controller
	recorder *MockClusterConfigWriterMockRecorder
	isgomock struct{}
}

// MockClusterConfigWriterMockRecorder is the mock recorder for MockClusterConfigWriter.
type MockClusterConfigWriterMockRecorder struct {
	mock *MockClusterConfigWriter
}

// NewMockClusterConfigWriter creates a new mock instance.
func NewMockClusterConfigWriter(ctrl *gomock.Controller) *MockClusterConfigWriter {
	mock := &MockClusterConfigWriter{ctrl: ctrl}
	mock.recorder = &MockClusterConfigWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClusterConfigWriter) EXPECT() *MockClusterConfigWriterMockRecorder {
	return m.recorder
}

// Write mocks base method.
func (m *MockClusterConfigWriter) Write(ctx context.Context, routineName string, timestamp time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", ctx, routineName, timestamp)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockClusterConfigWriterMockRecorder) Write(ctx, routineName, timestamp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockClusterConfigWriter)(nil).Write), ctx, routineName, timestamp)
}

// MockCancelableBackupHandler is a mock of CancelableBackupHandler interface.
type MockCancelableBackupHandler struct {
	ctrl     *gomock.Controller
	recorder *MockCancelableBackupHandlerMockRecorder
	isgomock struct{}
}

// MockCancelableBackupHandlerMockRecorder is the mock recorder for MockCancelableBackupHandler.
type MockCancelableBackupHandlerMockRecorder struct {
	mock *MockCancelableBackupHandler
}

// NewMockCancelableBackupHandler creates a new mock instance.
func NewMockCancelableBackupHandler(ctrl *gomock.Controller) *MockCancelableBackupHandler {
	mock := &MockCancelableBackupHandler{ctrl: ctrl}
	mock.recorder = &MockCancelableBackupHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCancelableBackupHandler) EXPECT() *MockCancelableBackupHandlerMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockCancelableBackupHandler) Cancel() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Cancel")
}

// Cancel indicates an expected call of Cancel.
func (mr *MockCancelableBackupHandlerMockRecorder) Cancel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockCancelableBackupHandler)(nil).Cancel))
}

// GetMetrics mocks base method.
func (m *MockCancelableBackupHandler) GetMetrics() *models.Metrics {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetrics")
	ret0, _ := ret[0].(*models.Metrics)
	return ret0
}

// GetMetrics indicates an expected call of GetMetrics.
func (mr *MockCancelableBackupHandlerMockRecorder) GetMetrics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetrics", reflect.TypeOf((*MockCancelableBackupHandler)(nil).GetMetrics))
}

// GetStats mocks base method.
func (m *MockCancelableBackupHandler) GetStats() *models.BackupStats {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats")
	ret0, _ := ret[0].(*models.BackupStats)
	return ret0
}

// GetStats indicates an expected call of GetStats.
func (mr *MockCancelableBackupHandlerMockRecorder) GetStats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockCancelableBackupHandler)(nil).GetStats))
}

// Wait mocks base method.
func (m *MockCancelableBackupHandler) Wait(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Wait", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Wait indicates an expected call of Wait.
func (mr *MockCancelableBackupHandlerMockRecorder) Wait(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wait", reflect.TypeOf((*MockCancelableBackupHandler)(nil).Wait), arg0)
}
