---
aerospike-clusters:
  cluster1:
    host: "127.0.0.1"
    port: 3000
    user: "admin"
    password: "admin"

storage:
  local1:
    type: 0
    path: "/var/lib/aerospike-backup-service"

backup-policies:
  policy1:
    type: 1
    parallel: 1
    remove-files: false

backup-routines:
  routine1:
    interval: 30000
    incr-interval: 5000
    backup-policy: "policy1"
    source-cluster: "cluster1"
    storage: "local1"
    namespace: "test"
