---
aerospike-clusters:
  cluster1:
    use-services-alternate: false
    seed-nodes:
      - host-name: "127.0.0.1"
        port: 3000
    credentials:
      user: "admin"
      password: "admin"

storage:
  local1:
    type: 0
    path: "/var/lib/aerospike-backup-service"

backup-policies:
  policy1:
    type: 1
    parallel: 1
    remove-files: false

backup-routines:
  routine1:
    interval-cron: "1/30 * * * * *" # every 30 seconds
    incr-interval-cron: "1/5 * * * * *" # every 5 seconds
    backup-policy: "policy1"
    source-cluster: "cluster1"
    storage: "local1"
    namespace: "test"
