//go:build integration

// Package integration holds the end-to-end tests of the backup service: ABS runs
// in-process against real Aerospike nodes, Secret Agent and storage emulators in
// Docker containers. A test that needs no container is a unit test and belongs
// next to the code it tests.
//
// The *_test.go files are the tests. suite_test.go declares the suites and their
// runners; every other *_test.go file declares only Test* methods, each with a doc
// comment saying what it checks. README.md lists them all, generated by `make docs`
// from those comments.
//
// The other files are the infrastructure the tests run on:
//
//	suite.go        Suite, the base every suite embeds, and PlainClusterSuite,
//	                which shares one plain Aerospike node
//	secured.go      SecuredClusterSuite: per-test Aerospike nodes with security
//	                and TLS enabled
//	names.go        the fixed names baseConfig registers (cluster, routine, …)
//	service.go      env: a running ABS instance, over HTTP or HTTPS
//	api.go          calls to the ABS REST API: trigger, list, wait, restore
//	metrics.go      reads of the ABS /metrics endpoint
//	assert.go       assertions on backups, restored records and metrics
//	aerospike.go    the plain Aerospike node shared by a suite
//	certs.go        a throwaway PKI for Aerospike TLS and the HTTPS listener
//	secretagent.go  Aerospike Secret Agent containers
//	minio.go        S3 (MinIO)
//	fakegcs.go      GCS (fake-gcs-server) and a fake OAuth token endpoint
//	azurite.go      Azure Blob (Azurite)
//	containers.go   container lifecycle and host-port pinning shared by the above
//	images.go       every image the suites use, pulled in parallel by TestMain
package integration
