name: Build
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - dev
      - main
      - 'v[0-9]+'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ 1.25.x ]
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Check go.mod
        run: |
          go mod tidy
          git diff --exit-code

      - name: Test
        run: |
          go test -race -tags=ci ./... -coverprofile=coverage.out -covermode=atomic
          grep -v -E -f .covignore coverage.out > coverage.filtered.out
          mv coverage.filtered.out coverage.out

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@303a32d7a59b442fa8d48b6a1cc6825c09c847a5 # v7.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build
        run: |
          cd cmd/backup
          go build -tags=ci .
