name: Build
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
      - 'v[0-9]+'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ 1.24.x ]
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: Setup Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Check go.mod
        run: |
          go mod tidy
          git diff --exit-code

      - name: Test
        run: |
          go test -race -tags=ci ./... -coverprofile=coverage.out -covermode=atomic
          grep -v -E -f .covignore coverage.out > coverage.filtered.out
          mv coverage.filtered.out coverage.out

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build
        run: |
          cd cmd/backup
          go build -tags=ci .
