name: Promote Images to DockerHub
on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Automation Code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Get Latest Tag
        run: |
          echo "TAG=$(cat VERSION | cut -c 2-)" >> $GITHUB_ENV
      - name: Get Repo Name
        id: variables_step
        run: |
          echo "repo_name=${GITHUB_REPOSITORY#*/}" >> "$GITHUB_OUTPUT"
      - name: Promote to DockerHub
        env:
          TAG: ${{env.TAG}}
          ARTIFACTORY_CONTAINER_PROD: ${{ vars.ARTIFACTORY_CONTAINER_PROD }}
        run: |
          docker buildx imagetools create \
          --tag "docker.io/aerospike/${{ steps.variables_step.outputs.repo_name }}:$TAG" \
          --tag "docker.io/aerospike/${{ steps.variables_step.outputs.repo_name }}:latest" \
          "aerospike.jfrog.io/$ARTIFACTORY_CONTAINER_PROD/${{ steps.variables_step.outputs.repo_name }}:$TAG"
