name: Promote Images to DockerHub
on:
  push:
    branches:
      - "APPS-1196-create-promote-to-docker-hub-action"
  workflow_dispatch:

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Automation Code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
      - name: Promote to DockerHub
        run: |
          docker buildx imagetools create \
          --tag "docker.io/davi17g/${GITHUB_REPOSITORY#*/}:${{ steps.get-latest-tag.outputs.tag }}" \
          --tag "docker.io/davi17g/${GITHUB_REPOSITORY#*/}:latest"
          "aerospike.jfrog.io/ecosystem-container-prod-local/${GITHUB_REPOSITORY#*/}:${{ steps.get-latest-tag.outputs.tag }}"
