name: Build Release Docker Images
on:
  workflow_dispatch:

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Automation Code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
#      - name: Promote to DockerHub
#        run: |
#          docker buildx imagetools create \
#          --tag "docker.io/davi17g/${{ github.event.inputs.service }}:${{ github.ref_name }}" \
#          --tag "docker.io/davi17g/${{ github.event.inputs.service }}:latest"
#          "aerospike.jfrog.io/ecosystem-container-prod-local/aerospike-backup-service:${{ github.ref_name }}"
      - name: Promote to DockerHub
        run: |
          echo "${GITHUB_REPOSITORY#*/}"
