name: Test Chart Install and Tests
on:
  pull_request:
    paths:
      - helm/aerospike-backup-service/**
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  lint-charts:
    runs-on: ubuntu-24.04
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          sparse-checkout: |
            helm/aerospike-backup-service
          sparse-checkout-cone-mode: true

      - name: Set up Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
        with:
          version: latest

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.11'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@6ec842c01de15ebb84c8627d2744a0c2f2755c9f # v2.8.0

      - name: Run chart-testing (lint)
        run: |
          cd helm/aerospike-backup-service
          ct lint --chart-dirs . --charts .

  test-chart:
    runs-on: ubuntu-24.04
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Install yq
        uses: dcarbone/install-yq-action@4075b4dca348d74bd83f2bf82d30f25d7c54539b #v1.3.1
        with:
          version: "v4.45.4"

      - name: Set up Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
        with:
          version: latest

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.x'
          check-latest: true

      - name: Set up Chart Testing
        uses: helm/chart-testing-action@6ec842c01de15ebb84c8627d2744a0c2f2755c9f # v2.8.0

      - name: Create Kind Cluster
        uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # v1.14.0

      - name: Build ABS Docker Container and Load to Kind Cluster
        run: |
          IMAGE_TAG="chart-testing" make docker-build
          kind load docker-image aerospike/aerospike-backup-service:chart-testing --name chart-testing

      - name: Setup Prerequisites
        run: |
          echo "Deploying AKO"

          curl -sL https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.35.0/install.sh | bash -s v0.35.0

          kubectl create -f https://operatorhub.io/install/aerospike-kubernetes-operator.yaml
          AKO_CSV_NAME="aerospike-kubernetes-operator.$(curl -s https://api.github.com/repos/aerospike/aerospike-kubernetes-operator/releases/latest | jq -r '.tag_name')"

          echo "Waiting for AKO"
          echo "Waiting for CSV to be created"
          kubectl wait --for=create "csv/$AKO_CSV_NAME" --namespace operators --timeout=300s
          echo "Waiting for CSV to be in Succeeded phase"
          kubectl wait --for=jsonpath='{.status.phase}'=Succeeded "csv/$AKO_CSV_NAME" --namespace operators --timeout=300s
          echo "Waiting for operator pods to be ready"
          kubectl wait --for=condition=Ready pod --all --namespace operators --timeout=300s

          echo "Grant permissions to the target namespace"
          kubectl create namespace aerospike
          kubectl --namespace aerospike create serviceaccount aerospike-operator-controller-manager
          kubectl create clusterrolebinding aerospike-cluster --clusterrole=aerospike-cluster --serviceaccount=aerospike:aerospike-operator-controller-manager

          echo "Set Secrets for Aerospike Cluster"
          kubectl --namespace aerospike create secret generic aerospike-secret --from-literal=features.conf="$(echo "${{ secrets.FEATURES_CONF }}")"
          kubectl --namespace aerospike create secret generic minio-credentials --from-file=credentials=<(cat <<EOF
          [minio]
          aws_access_key_id=minioadmin
          aws_secret_access_key=minioadmin
          EOF
          )

          echo "Deploy ASDB"
          ASDB_VERSION="$(curl -s "https://hub.docker.com/v2/repositories/aerospike/aerospike-server/tags?page_size=1024" | jq -r '[.results[].name | select(test("^\\d+\\.\\d+$"))] | sort_by(.) | reverse | .[1]').0"

          cat <<EOF | kubectl apply -f -
          apiVersion: asdb.aerospike.com/v1
          kind: AerospikeCluster
          metadata:
            name: aerocluster
            namespace: aerospike
          spec:
            aerospikeConfig:
              namespaces:
                - name: test
                  replication-factor: 2
                  storage-engine:
                    data-size: 1073741824
                    type: memory
              network:
                fabric:
                  port: 3001
                heartbeat:
                  port: 3002
                service:
                  port: 3000
              service:
                feature-key-file: /etc/aerospike/secret/features.conf
            image: "aerospike/aerospike-server-enterprise:${ASDB_VERSION}"
            podSpec:
              multiPodPerHost: true
            size: 2
            storage:
              volumes:
                - aerospike:
                    path: /etc/aerospike/secret
                  name: aerospike-config-secret
                  source:
                    secret:
                      secretName: aerospike-secret
            validationPolicy:
              skipWorkDirValidate: true
              skipXdrDlogFileValidate: true
          EOF

      - name: Run chart-testing (install)
        env:
          GITHUB_BRANCH: ${{ github.ref_name }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
        run: |
          yq eval '. as $item ireduce ({}; .backupServiceConfig = $item)' .github/config/test-chart-abs-conf.yaml > abs-values.yaml
          cat <<EOF > ct-values.yaml
          volumes:
            - name: minio-credentials
              secret:
                secretName: minio-credentials
                optional: false
          extraSecretVolumeMounts:
            - name: minio-credentials
              mountPath: /home/absuser/.aws/credentials
              readOnly: true
          image:
            pullPolicy: IfNotPresent
            tag: chart-testing
          configmap:
            create: false
          EOF

          ct install \
          --namespace aerospike \
          --chart-dirs helm \
          --target-branch "$GITHUB_DEFAULT_BRANCH" \
          --debug --helm-extra-args="--debug" \
          --helm-extra-set-args="--values=ct-values.yaml --values=abs-values.yaml"
