name: Link Check

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - dev
      - main
      - 'v[0-9]+'

permissions:
  contents: read

jobs:
  lychee:
    name: markdown links
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: Checkout sources
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Link Checker
        uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 # v2.9.0
        with:
          args: --config .lychee.toml .
          fail: true
          jobSummary: true
