name: Create a Release and Push Release assets
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Check if release exists
        id: check-release
        uses: actions/github-script@v7
        with:
          script: |
            const octokit = github.getOctokit();
            try {
              const response = await octokit.rest.repos.getReleaseByTag({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag: '${{ github.ref }}'
              });

              if (response.status === 200) {
                console.log(`Release with tag ${tag} exists.`);
                core.setOutput('release-exists', 'true');
              }
            } catch (error) {
              if (error.status === 404) {
                console.log(`Release with tag ${tag} does not exist.`);
                core.setOutput('release-exists', 'false');
              } else {
                throw error;
              }
            }
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/create-release@v1
        if: ${{ steps.check-release.outputs.release-exists == 'false'}}
        id: create-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: true
  build-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        name: build images
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            try {
                const result = await github.rest.actions.createWorkflowDispatch({
                  owner: '${{ secrets.ORG }}',
                  repo: '${{ secrets.REPO }}',
                  workflow_id: 'release.yml',
                  ref: 'APPS-1189-improve-release-github-action-workflow',
              })
              console.log(result);
            } catch(error) {
              console.error(error);
              core.setFailed(error);
            }
  build-packages:
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        arch: ["amd64","arm64"]
        container: [ "rhel8:latest", "rhel9:latest", "ubuntu2204:latest"]
        include:
          - container: "rhel8:latest"
            cmd: "make rpm"
            distro_symbol: "el8"
            ext: "rpm"
          - container: "rhel9:latest"
            cmd: "make rpm"
            distro_symbol: "el9"
            ext: "rpm"
          - container: "ubuntu2204:latest"
            cmd: "make deb"
            distro_symbol: "debian"
            ext: "deb"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Jfrog
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: ${{ secrets.ARTIFACTORY_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
      - name: Login to JFrog
        uses: docker/login-action@v2
        with:
          registry: aerospike.jfrog.io
          username: ${{ secrets.ARTIFACTORY_USER }}
          password: ${{ secrets.ARTIFACTORY_TOKEN }}
      - name: Create target directory
        run: mkdir -p ${{ github.workspace }}/target
      - name: Create lib directory
        run: mkdir -p ${{ github.workspace }}/lib
      - name: Build artifact
        id: build-artifact
        run: |
          docker run -v ${{ github.workspace }}:/aerospike-backup-service/ \
          -w /aerospike-backup-service/ \
          --platform linux/${{ matrix.arch }} aerospike.jfrog.io/ecosystem-container-dev-local/base-${{ matrix.container }} ${{ matrix.cmd }}
      - name: Set variable arch variable based on condition
        id: set-variables
        run: |
          if [ "${{ matrix.arch }}" == "arm64" ]; then
            echo "arch=aarch64" >> $GITHUB_OUTPUT
          else
            echo "arch=x86_64" >> $GITHUB_OUTPUT
          fi
          REPO_NAME="$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)"
          echo "repo=$REPO_NAME" >> $GITHUB_OUTPUT
          VERSION="$(cat VERSION)"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Checksum the package
        id: package-checksum
        run: |
          if [ "${{ matrix.ext }}" == "rpm" ]; then
            sha256sum ${{ github.workspace }}/target/${{ steps.set-variables.outputs.repo }}-${{ steps.set-variables.outputs.version }}-1.${{ matrix.distro_symbol }}.${{ steps.set-variables.outputs.arch }}.${{ matrix.ext }} | cut -d' ' -f1 > \
              ${{ github.workspace }}/target/${{ steps.set-variables.outputs.repo }}-${{ steps.set-variables.outputs.version }}-1.${{ matrix.distro_symbol }}.${{ steps.set-variables.outputs.arch }}.${{ matrix.ext }}.sha256
          fi
          
          if [ "${{ matrix.ext }}" == "deb" ]; then
            sha256sum ${{ github.workspace }}/target/${{ steps.set-variables.outputs.repo }}_${{ steps.set-variables.outputs.version }}-1_${{ matrix.arch }}.${{ matrix.ext }} | cut -d' ' -f1 > \
              ${{ github.workspace }}/target/${{ steps.set-variables.outputs.repo }}_${{ steps.set-variables.outputs.version }}-1_${{ matrix.arch }}.${{ matrix.ext }}.sha256
          fi
      - uses: actions/upload-release-asset@v1
        if: ${{ matrix.ext == 'rpm' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/target/${{ steps.set-variables.outputs.repo }}-${{ steps.set-variables.outputs.version }}-1.${{ matrix.distro_symbol }}.${{ steps.set-variables.outputs.arch }}.${{ matrix.ext }}
          asset_name: ${{ steps.set-variables.outputs.repo }}-${{ steps.set-variables.outputs.version }}-1.${{ matrix.distro_symbol }}.${{ steps.set-variables.outputs.arch }}.${{ matrix.ext }}
          asset_content_type: application/x-${{ matrix.ext }}
      - uses: actions/upload-release-asset@v1
        if: ${{ matrix.ext == 'rpm' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/target/${{ steps.set-variables.outputs.repo }}-${{ steps.set-variables.outputs.version }}-1.${{ matrix.distro_symbol }}.${{ steps.set-variables.outputs.arch }}.${{ matrix.ext }}.sha256
          asset_name: ${{ steps.set-variables.outputs.repo }}-${{ steps.set-variables.outputs.version }}-1.${{ matrix.distro_symbol }}.${{ steps.set-variables.outputs.arch }}.${{ matrix.ext }}.sha256
          asset_content_type: text/plain
      - uses: actions/upload-release-asset@v1
        if: ${{ matrix.ext == 'deb' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/target/${{ steps.set-variables.outputs.repo }}_${{ steps.set-variables.outputs.version }}-1_${{ matrix.arch }}.${{ matrix.ext }}
          asset_name: ${{ steps.set-variables.outputs.repo }}_${{ steps.set-variables.outputs.version }}-1_${{ matrix.arch }}.${{ matrix.ext }}
          asset_content_type: application/x-${{ matrix.ext }}
      - uses: actions/upload-release-asset@v1
        if: ${{ matrix.ext == 'deb' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/target/${{ steps.set-variables.outputs.repo }}_${{ steps.set-variables.outputs.version }}-1_${{ matrix.arch }}.${{ matrix.ext }}.sha256
          asset_name: ${{ steps.set-variables.outputs.repo }}_${{ steps.set-variables.outputs.version }}-1_${{ matrix.arch }}.${{ matrix.ext }}.sha256
          asset_content_type: text/plain
