name: test
on:
  push:
    branches:
      - APPS-1189-improve-release-github-action-workflow
  workflow_dispatch:
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository:  citrusleaf/ecosystem-automation
          event-type: my-event