name: Test
on:
  push:
    branches:
      - APPS-1189-improve-release-github-action-workflow
  workflow_dispatch:
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        name: Invoke docker image build
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: ${{ secrets.ORG }},
              repo: ${{ secrets.REPO }},
              workflow_id: 'hello-wold.yaml',
              ref: 'APPS-1189-improve-release-github-action-workflow'
              })