name: test
on:
  push:
    branches:
      - APPS-1189-improve-release-github-action-workflow
  workflow_dispatch:
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        name: Invoke docker image build
        with:
          debug: true
          github-token: ${{ secrets.PAT }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: citrusleaf,
              repo: ecosystem-automation,
              workflow_id: 'hello-world.yml',
              ref: 'APPS-1189-improve-release-github-action-workflow'
            })
