name: Validate aerospike-backup-service configuration against JSON Schema
on:
  pull_request:
  workflow_dispatch:

jobs:
  validate-abs-config-file:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install check-jsonschema

      - name: Install yq
        uses: dcarbone/install-yq-action@4075b4dca348d74bd83f2bf82d30f25d7c54539b #v1.3.1
        with:
          version: "v4.45.4"

      - name: Validate aerospike-backup-service.yml files against config.schema.json
        run: |
          find . -type f -name 'aerospike-backup-service.yml' | while read -r file; do
            echo "Validating $file"
            check-jsonschema --verbose --schemafile /docs/config.schema.json $file 
          done
          check-jsonschema --verbose --schemafile /docs/config.schema.json .github/samples/test-chart-abs-conf.yaml
          check-jsonschema --verbose --schemafile /docs/config.schema.json config/config.yml
          check-jsonschema --verbose --schemafile /docs/config.schema.json config/minio_config.yml
