name: Validate aerospike-backup-service configuration against JSON Schema

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  validate-abs-config-file:
    runs-on: ubuntu-24.04

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install check-jsonschema

      - name: Install yq
        uses: dcarbone/install-yq-action@4075b4dca348d74bd83f2bf82d30f25d7c54539b #v1.3.1
        with:
          version: "v4.45.4"

      - name: Validate aerospike-backup-service.yml files against config.schema.json
        run: |
          echo "Starting JSON Schema validation using check-jsonschema"
          echo "Using schema: ./docs/config.schema.json"
          echo "------------------------------------------------------------"
          
          SCHEMA=./docs/config.schema.json
          EXIT_CODE=0
          
          echo "Searching for all aerospike-backup-service.yml files..."
          find . -type f -name 'aerospike-backup-service.yml' | while read -r file; do
            echo ""
            echo "Validating dynamically discovered file: $file"
            if check-jsonschema --verbose --schemafile "$SCHEMA" "$file"; then
              echo "PASSED: $file"
            else
              echo "FAILED: $file"
              EXIT_CODE=1
            fi
          done
          
          echo ""
          echo "Validating additional explicitly listed files..."
          
          for file in \
            .github/config/test-chart-abs-conf.yaml \
            ./config/config.yml \
            ./config/minio_config.yml
          do
            echo ""
            echo "Validating file: $file"
            if check-jsonschema --verbose --schemafile "$SCHEMA" "$file"; then
              echo "PASSED: $file"
            else
              echo "FAILED: $file"
              EXIT_CODE=1
            fi
          done
          
          echo ""
          echo "------------------------------------------------------------"
          if [ "$EXIT_CODE" -ne 0 ]; then
            echo "One or more files failed schema validation"
          else
            echo "All files passed schema validation"
          fi
          
          exit $EXIT_CODE
